#include "../util/utility_afx.h"
#include <vector>
#include <chrono>
#include <map>
#include <set>
#include "../util/dynamic_string.h"
#include "../util/utility.h"
#include "../util/filename_struct.h"
#include "../util/Timestamp.h"
#include "../util/interface_window.h"
#include "../util/device_coordinate.h"
#include "../util/state_names.h"
#include "../map/color_set.h"
#include "../util/bounding_cube.h"
#include "../map/dynamic_map.h"
#include "../map/map_scale.h"
#include "../map/dbase.h"
#include "../map/shapefile.h"
#include "../map/shapefile_filter.h"
#include "PipelineAccidents.h"
#include "../cardgis_console/flow_network_divergence.h"
#include "../cardgis_console/flow_network_link.h"
#include "../cardgis_console/router_NHD.h"

void pipeline_zillow_point_callback
	(const map_object *point,
	const char delimiter,
	dynamic_string &log)

// Called by work_MapLayerProximity to write identifiers & data for Zillow Sales point

{
	// int state_fips, county_fips;

	// ID\tRow ID\tTrans ID\tImportParcelID
	// \tPropertyFullStreetAddress\tSalesDate\tStateFIPS\tCountyFIPS\tSalesPriceAmount\tLot Size ft^2\tlatitude\tlongitude
	// \tLAGOS ID\tdistance, m\t9 month chla\t12 month chla
	log.add_formatted ("%ld", point->id);
	log += delimiter;
	log += "\"";
	log += point->name; // RowID
	log += "\"";
	log += delimiter;

	log += "\"";
	log += point->attributes_text [0]; // Trans ID
	log += "\"";

	log += delimiter;
	log.add_formatted ("%.1lf", point->attributes_numeric [0]); // ImportParcelID

	/*
	// 2021-04-20 2021-04-20 Wendong: Drop these columns to save time
	log += delimiter;
	log += point->attributes_text [1];// PropertyFullStreetAddress
	log += delimiter;
	if (point->attributes_void)
		log += ((Timestamp *) point->attributes_void)->write (TIMESTAMP_YYYY_MM_DD);// Sales Date

	state_fips = (int) point->attributes_numeric[2];
	county_fips = state_fips % 1000;
	state_fips = (state_fips - county_fips) / 1000;
	log.add_formatted ("%c%d%c%d", delimiter, state_fips, delimiter, county_fips);

	log.add_formatted ("%c%.2lf", delimiter, point->attributes_numeric [1]); // SalesPriceAmount
	log.add_formatted ("%c%.2lf", delimiter, point->attributes_numeric [3]); // LotSizeSquareFeet

	log.add_formatted ("%c%.8lf%c%.8lf", delimiter, (double) point->latitude / 1.0e6, delimiter, (double) point->longitude / 1.0e6);
	*/

	// Gas Distribution 10 mi.
	// Gas Gathering 10 mi.
	// Hazardous Liquid 10 mi.
	// Liquified Natural Gas 10 mi.
	// See ZillowSales.read_csv_format_3 for base index count of attributes_numeric
	log.add_formatted ("%c%ld%c%ld%c%ld%c%ld",
	delimiter, (long) point->attributes_numeric [2],
	delimiter, (long) point->attributes_numeric [3],
	delimiter, (long) point->attributes_numeric [4],
	delimiter, (long) point->attributes_numeric [5]);
}

void pipeline_callback
	(const map_object *point,
	const double distance_m,
	const char delimiter,
	dynamic_string &log)

// One column per pipeline incident type

{
	// log += delimiter;
	// log.add_formatted ("%ld", point->id);
	log += delimiter;
	log.add_formatted ("%.6lf", distance_m);

}

void gas_distribution_column_header_callback
	(const char delimiter,
	dynamic_string &column_names)
{
	column_names.clear ();
	column_names += delimiter;
	column_names += "\"GD incident distance, m\"";
}
void gas_gathering_column_header_callback
	(const char delimiter,
	dynamic_string &column_names)
{
	column_names.clear ();
	column_names += delimiter;
	column_names += "\"GTGG incident distance, m\"";
}
void hazardous_liquid_column_header_callback
	(const char delimiter,
	dynamic_string &column_names)
{
	column_names.clear ();
	column_names += delimiter;
	column_names += "\"HL incident distance, m\"";
}
void liquified_natural_gas_column_header_callback
	(const char delimiter,
	dynamic_string &column_names)
{
	column_names.clear ();
	column_names += delimiter;
	column_names += "\"LNG incident distance, m\"";
}

void pipeline_zillow_point_callback_10mi
	(const map_object *point,
	const char delimiter,
	dynamic_string &log)

// Called by work_MapLayerProximity to write identifiers & data for Zillow Sales point

{
	// int state_fips, county_fips;

	// ID\tRow ID\tTrans ID\tImportParcelID
	// \tPropertyFullStreetAddress\tSalesDate\tStateFIPS\tCountyFIPS\tSalesPriceAmount\tLot Size ft^2\tlatitude\tlongitude
	// \tLAGOS ID\tdistance, m\t9 month chla\t12 month chla
	log.add_formatted ("%ld", point->id);
	log += delimiter;
	log += "\"";
	log += point->name; // RowID
	log += "\"";
	log += delimiter;

	log += "\"";
	log += point->attributes_text [0]; // Trans ID
	log += "\"";

	log += delimiter;
	log.add_formatted ("%.1lf", point->attributes_numeric [0]); // ImportParcelID
}

void pipeline_callback_10mi
	(const map_object *point,
	const double distance_m,
	const char delimiter,
	dynamic_string &log)

{
	log += delimiter;
	log.add_formatted ("%.6lf", distance_m);
	log += delimiter;
	log.add_formatted ("%ld", point->id);
	log += delimiter;
	log.add_formatted ("%.6lf", (double) point->latitude / 1.0e6);
	log += delimiter;
	log.add_formatted ("%.6lf", (double) point->longitude / 1.0e6);

}

void pipeline_column_header_callback_10mi
	(const char delimiter,
	dynamic_string &column_names)
{
	column_names.clear ();
	column_names += delimiter;
	column_names += "\"Incident Distance, m\"";
	column_names += delimiter;
	column_names += "\"Report Number\"";
	column_names += delimiter;
	column_names += "\"Latitude\"";
	column_names += delimiter;
	column_names += "\"Longitude\"";
}

/*
PipelineIncident::PipelineIncident ()

{
	Report_Number = 0L;
	Operator_ID = 0L;
	Location_Latitude = 0.0;
	Location_Longitude = 0.0;
	Unintentional_Release = 0.0;
}

PipelineIncident::PipelineIncident
	(const PipelineIncident &other)

{
	copy (other);
}

PipelineIncident PipelineIncident::operator =
	(const PipelineIncident &other)
{
	if (this != &other)
		copy(other);

	return (*this);
}

void PipelineIncident::copy
	(const PipelineIncident &other)
{
	Local_DateTime = other.Local_DateTime;
	Report_Number = other.Report_Number;
	Operator_ID = other.Operator_ID;
	Location_Latitude = other.Location_Latitude;
	Location_Longitude = other.Location_Longitude;
	Unintentional_Release = other.Unintentional_Release;
}

void PipelineIncident::clear ()
{
	Local_DateTime.clear ();
	Report_Number = 0L;
	Operator_ID = 0L;
	Location_Latitude = 0.0;
	Location_Longitude = 0.0;
	Unintentional_Release = 0.0;
}
*/

PipelineAccidents::PipelineAccidents ()
{
	layer_gd = NULL;
}


PipelineAccidents::~PipelineAccidents ()
{
}

bool PipelineAccidents::read_gas_distribution
	(dynamic_string &filename,
	interface_window *view,
	dynamic_string &log)

{
	FILE *f;
	dynamic_string data;
	char buffer[16384];
	map_object *leak;
	std::vector <dynamic_string> tokens;

	view->update_progress (filename, 1);

	if (fopen_s (&f, filename.get_text_ascii (), "r") == 0) {
		// DATAFILE_AS_OF	FF	SIGNIFICANT	SERIOUS	REPORT_NUMBER	SUPPLEMENTAL_NUMBER	REPORT_RECEIVED_DATE	REPORT_TYPE	OPERATOR_ID	NAME	OPERATOR_STREET_ADDRESS	OPERATOR_CITY_NAME	OPERATOR_STATE_ABBREVIATION	OPERATOR_POSTAL_CODE	LOCAL_DATETIME	TIME_ZONE	DAYLIGHT_SAVINGS_IND	IYEAR	LOCATION_STREET_ADDRESS	LOCATION_CITY_NAME	LOCATION_COUNTY_NAME	LOCATION_STATE_ABBREVIATION	LOCATION_POSTAL_CODE	LOCATION_LATITUDE	LOCATION_LONGITUDE	NRC_RPT_NUM	ADDITIONAL_NRC_REPORT_NUMBERS	FLOW_CONT_KEY_CRIT_IND	FLOW_CONT_MAIN_VALVE_IND	FLOW_CONT_SERVICE_VALVE_IND	FLOW_CONT_METER_REG_IND	FLOW_CONT_EXCESS_FLOW_IND	FLOW_CONT_SQUEEZE_OFF_IND	FLOW_CONT_STOPPLE_FITNG_IND	FLOW_CONT_OTHER_IND	FLOW_CONT_OTHER_DETAIL	NRC_RPT_DATETIME	COMMODITY_RELEASED_TYPE	COMMODITY_DETAILS	UNINTENTIONAL_RELEASE	INTENTIONAL_RELEASE	FATALITY_IND	NUM_EMP_FATALITIES	NUM_CONTR_FATALITIES	NUM_ER_FATALITIES	NUM_WORKER_FATALITIES	NUM_GP_FATALITIES	FATAL	INJURY_IND	NUM_EMP_INJURIES	NUM_CONTR_INJURIES	NUM_ER_INJURIES	NUM_WORKER_INJURIES	NUM_GP_INJURIES	INJURE	IGNITE_IND	IGNITE_DATETIME	HOW_EXTINGUISHED	HOW_EXTINGUISHED_OTHER_DETAIL	GAS_CONSUMED_BY_FIRE_IN_MCF	EXPLODE_IND	NUM_PUB_EVACUATED	INCIDENT_IDENTIFIED_DATETIME	COMMUNICATION_STATE_FED_IND	PARTY_INITIATED_COMMUNICATION	INITIAL_RESPONDER_COM_DATETIME	ON_SITE_DATETIME	FEDERAL	LOCATION_TYPE	INCIDENT_AREA_TYPE	INCIDENT_AREA_SUBTYPE	INCIDENT_AREA_DETAILS	DEPTH_OF_COVER	OTHER_UNDERGROUND_FACILITIES	CROSSING	BRIDGE_CROSSING_IND	BRIDGE_TYPE	RAILROAD_CROSSING_IND	RAILROAD_TYPE	ROAD_CROSSING_IND	ROAD_TYPE	WATER_CROSSING_IND	WATER_TYPE	WATER_NAME	WATER_DEPTH	WATER_SUBTYPE	PIPE_FACILITY_TYPE	PIPE_TYPE_OTHER	SYSTEM_PART_INVOLVED	SYSTEM_PART_DETAILS	INSTALLATION_YEAR	MANUFACTURED_YEAR	CUSTOMER_TYPE	WAS_EFV_INSTALLED_BEFORE_IND	EVF_ACTIVATION_IND	CURB_VALVE_INST_BEFORE_INC_IND	PIPE_DIAMETER	PIPE_SPECIFICATION	PIPE_MANUFACTURER	MATERIAL_INVOLVED	MATERIAL_DETAILS	STEEL_SEAM_TYPE	STEEL_SEAM_TYPE_DETAILS	WT_STEEL	PLASTIC_TYPE	PLASTIC_DETAILS	PLASTIC_SDR	WT_PLASTIC	WT_PLASTIC_UNKNOWN_IND	MATERIAL_PE_PIPE_CODE	RELEASE_TYPE	PUNCTURE_AXIAL	PUNCTURE_CIRCUM	LEAK_TYPE	LEAK_TYPE_OTHER	RUPTURE_ORIENT	RUPTURE_DETAILS	RUPTURE_LENGTH	RUPTURE_WIDTH	RELEASE_TYPE_DETAILS	CLASS_LOCATION_TYPE	EST_COST_OPER_PAID	EST_COST_OPER_PAID_CURRENT	EST_COST_PROP_DAMAGE	EST_COST_PROP_DAMAGE_CURRENT	EST_COST_EMERGENCY	EST_COST_EMERGENCY_CURRENT	EST_COST_OTHER	EST_COST_OTHER_CURRENT	EST_COST_OTHER_DETAILS	GAS_COST_IN_MCF	EST_COST_UNINTENTIONAL_RELEASE	EST_COST_UNINTENT_REL_CURRENT	EST_COST_INTENTIONAL_RELEASE	EST_COST_INTENT_REL_CURRENT	TOTAL_COST	TOTAL_COST_IN84	TOTAL_COST_CURRENT	COMMERCIAL_AFFECTED	INDUSTRIAL_AFFECTED	RESIDENCES_AFFECTED	NUM_PERSONS_HOSP_NOT_OVNGHT	NUM_INJURED_TREATED_BY_EMT	NUM_RESIDENT_BUILDING_AFFCTD	NUM_BUSINESS_BUILDING_AFFCTD	ACCIDENT_PSIG	NORMAL_PSIG	MOP_PSIG	MOP_CFR_SECTION	MAOP_ESTABLISHED_DATE	ACCIDENT_PRESSURE	GAS_ODORIZED_SYSTEM_TYPE	GAS_ODORIZED_SYS_OTHER_DETAIL	GAS_ODORIZED_LEVEL	GAS_ODORIZED_LVL_NOT_MSRD_IND	SCADA_IN_PLACE_IND	SCADA_OPERATING_IND	SCADA_FUNCTIONAL_IND	SCADA_DETECTION_IND	SCADA_CONF_IND	ACCIDENT_IDENTIFIER	ACCIDENT_DETAILS	OPERATOR_TYPE	INVESTIGATION_STATUS	INVESTIGATION_STATUS_DETAILS	INVEST_SCHEDULE_IND	INVEST_NO_SCHEDULE_IND	INVEST_NO_SCHEDULE_IND_DETAILS	INVEST_NO_CONTROL_ROOM_IND	INVEST_NO_CONTROLLER_IND	INVEST_INCORRECT_ACTION_IND	INVEST_FATIGUE_IND	INVEST_INCORRECT_PROCEDURE_IND	INVEST_INCORRECT_CONTROL_IND	INVEST_MAINT_IND	INVEST_OTHER_IND	INVEST_OTHER_IND_DETAILS	EMPLOYEE_DRUG_TEST_IND	NUM_EMPLOYEES_TESTED	NUM_EMPLOYEES_FAILED	CONTRACTOR_DRUG_TEST_IND	NUM_CONTRACTORS_TESTED	NUM_CONTRACTORS_FAILED	CAUSE	CAUSE_DETAILS	MAP_CAUSE	MAP_SUBCAUSE	INTERNAL_EXTERNAL	VISUAL_EXAM_RESULTS	VISUAL_EXAM_DETAILS	GALVANIC_CORROSION_IND	ATMOSPHERE_CORROSION_IND	STRAY_CURRENT_CORROSION_IND	MICROBIOLOGICAL_CORROSION_IND	SELECTIVE_SEAM_CORROSION_IND	OTHER_CORROSION_IND	CORROSION_TYPE_DETAILS	STRAY_CURRENT_TYPE	STRAY_CURRENT_DETAILS	FIELD_EXAM_BASIS_IND	METALLURGICAL_BASIS_IND	OTHER_BASIS_IND	CORROSION_BASIS_DETAILS	UNDERGROUND_LOCATION	UNDER_CATHODIC_PROTECTION_IND	CATHODIC_PRO_START_YEAR	SHIELDING_EVIDENT	CATHODIC_SURVEY_TYPE	CP_ANNUAL_SURVEY_IND	CLOSE_INTERVAL_SURVEY_IND	OTHER_CP_SURVEY_IND	CP_ANNUAL_SURVEY_YEAR	CLOSE_INTERVAL_SURVEY_YEAR	OTHER_CP_SURVEY_YEAR	OTHER_CP_SURVEY_DETAILS	EXTERNALLY_COATED	PRIOR_DAMAGE	COATING_TYPE	COATING_TYPE_DETAILS	FIELD_APPLIED_IND	INT_VISUAL_EXAM_RESULTS	INT_VISUAL_EXAM_DETAILS	INT_CORROSIVE_COMMODITY_IND	INT_WATER_ACID_IND	INT_MICROBIOLOGICAL_IND	INT_EROSION_IND	INT_OTHER_CORROSION_IND	INT_CORROSION_TYPE_DETAILS	INT_FIELD_EXAM_BASIS_IND	INT_METALLURGICAL_BASIS_IND	INT_OTHER_BASIS_IND	INT_CORROSION_BASIS_DETAILS	INT_LOW_POINT_PIPE_LOC_IND	INT_ELBOW_LOC_IND	INT_DROP_OUT_LOC_IND	INT_OTHER_LOC_IND	CORROSION_LOCATION_DETAILS	CORROSION_INHIBITORS	LIQUID_FOUND	COR_HYDROTEST_LEAK_SURVEY_DATE	COR_HYDROTEST_CONDUCTED_IND	COR_HYDROTEST_CONDUCTED_YEAR	COR_HYDROTEST_PRESSURE	NATURAL_FORCE_TYPE	EARTH_SUBTYPE	HEAVY_RAINS_SUBTYPE	LIGHTNING_SUBTYPE	TEMPERATURE_SUBTYPE	NF_OTHER_DETAILS	NF_EXTREME_WEATHER_IND	NF_HURRICANE_IND	NF_TROPICAL_STORM_IND	NF_TORNADO_IND	NF_OTHER_IND	NF_EXTREME_WEATHER_DETAILS	PARTY_TYPE	EX_HYDROTEST_LEAK_SURVEY_DATE	EX_HYDROTEST_CONDUCTED_IND	EX_HYDROTEST_CONDUCTED_YEAR	EX_HYDROTEST_PRESSURE	PRIOR_NOTIFICATION_IND	ONE_CALL_SYSTEM_IND	EXCAVATOR_IND	CONTRACTOR_IND	LANDOWNER_IND	STATE_LAW_EXEMPT_IND	STATE_LAW_EXEMPT_TYPE	STATE_LAW_EXEMPT_DETAIL	STATE_LAW_EXEMPT_AUTHORITY	STATE_LAW_EXEMPT_CRITERIA	NOTIFY_CGA_DIRT	PUBLIC_ROW_IND	PUBLIC_SUBTYPE	PRIVATE_ROW_IND	PRIVATE_SUBTYPE	PIPELINE_EASEMENT_ROW_IND	POWER_TRANSMISSION_ROW_IND	RAILROAD_ROW_IND	PUBLIC_UTIL_EASEMENT_ROW_IND	FEDERAL_LAND_ROW_IND	DATA_NOT_COLLECTED_ROW_IND	UNKNOWN_ROW_IND	EXCAVATOR_TYPE	EXCAVATOR_EQUIPMENT	WORK_PERFORMED	ONE_CALL_NOTIFIED_IND	ONE_CALL_TICKET_NUM	ONE_CALL_CENTER_NAME	LOCATOR_TYPE	VISIBLE_MARKS	FACILITIES_MARKED	SERVICE_INTERRUPTION	SERVICE_INTERRUPTION_HOURS	ROOT_CAUSE	ROOT_CAUSE_OTHER	ONE_CALL_SUBTYPE	LOCATING_SUBTYPE	EXCAVATION_SUBTYPE	OUTSIDE_FORCE_TYPE	VEHICLE_SUBTYPE	OSF_HURRICANE_IND	OSF_TROPICAL_STORM_IND	OSF_TORNADO_IND	OSF_HEAVY_RAINS_IND	OSF_OTHER_WEATHER_IND	OSF_OTHER_WEATHER_DETAILS	OSF_HYDROTEST_LEAK_SURVEY_DATE	OSF_HYDROTEST_CONDUCTED_IND	OSF_HYDROTEST_CONDUCTED_YEAR	OSF_HYDROTEST_PRESSURE	INTENTIONAL_SUBTYPE	INTENTIONAL_DETAILS	OSF_OTHER_DETAILS	DRIVER_ISSUED_CITATION_IND	CITATION_SPEED_IND	CITATION_RECKLESS_IND	CITATION_DUI_IND	CITATION_OTHER_IND	CITATION_OTHER_DETAIL	DRIVER_IN_CONTROL_IND	ESTIMATED_SPEED	VEHICLE_TYPE	VEHICLE_TRAVEL_FROM	VEHICLE_TRAVEL_DISTANCE_FT	PROTECTIONS_INSTALLED_IND	PROTECTION_BOLLARDS_POST_IND	PROTECTION_BARRICADES_IND	PROTECTION_GUARD_RAILS_IND	PROTECTION_METER_BOX_IND	PROTECTION_INGRESS_REGRESS_IND	PROTECTION_OTHER_IND	PROTECTION_OTHER_DETAIL	PWJF_FAILURE_TYPE	PIPE_BODY_SUBTYPE	PIPE_BODY_DETAILS	BUTT_WELD_SUBTYPE	BUTT_WELD_DETAILS	FILLET_WELD_SUBTYPE	FILLET_WELD_DETAILS	PIPE_SEAM_SUBTYPE	PIPE_SEAM_DETAILS	PHMSA_7100_1_2_REPORT_ID	PHMSA_7100_1_2_PENDING_IND	PLASTIC_JOINT_SUBTYPE	PLASTIC_JOINT_DETAILS	FPW_INSTALLED_YEAR	FPW_OTHER_ATTR	FPW_FIRST_PLASTIC_TYPE	FPW_FIRST_PLASTIC_TYPE_OTHER	FPW_SECOND_PLASTIC_TYPE	FPW_SECOND_PLASTIC_TYPE_OTHER	PWJF_FAILURE_DETAILS	ADDITIONAL_DENT_IND	ADDITIONAL_GOUGE_IND	ADDITIONAL_PIPE_BEND_IND	ADDITIONAL_ARC_BURN_IND	ADDITIONAL_CRACK_IND	ADDITIONAL_LACK_FUSION_IND	ADDITIONAL_LAMINATION_IND	ADDITIONAL_BUCKLE_IND	ADDITIONAL_WRINKLE_IND	ADDITIONAL_MISALIGNMENT_IND	ADDITIONAL_BURNT_STEEL_IND	ADDITIONAL_OTHER_IND	ADDITIONAL_FACTOR_DETAILS	RESULT_CONSTRUCTION_IND	RESULT_MATERIAL_IND	RESULT_DESIGN_IND	RESULT_PREVIOUS_IND	RESULT_CONSTRUCTION_SUBTYPE	RESULT_MATERIAL_SUBTYPE	RESULT_MATERIAL_DETAILS	HYDROTEST_CONDUCTED_IND	HYDROTEST_CONDUCTED_YEAR	HYDROTEST_PRESSURE	EQ_FAILURE_TYPE	CONTROL_VALVE_IND	INSTRUMENTATION_IND	SCADA_IND	COMMUNICATIONS_IND	BLOCK_VALVE_IND	CHECK_VALVE_IND	RELIEF_VALVE_IND	POWER_FAILURE_IND	STOPPLE_CONTROL_FITTING_IND	PRESSURE_REGULATOR_IND	OTHER_CONTROL_RELIEF_IND	OTHER_CONTROL_RELIEF_DETAILS	OTHER_STRIPPED_IND	OTHER_STRIPPED_DETAILS	OTHER_NON_THREADED_IND	OTHER_NON_THREADED_DETAILS	VALVE_OTHER_IND	VALVE_OTHER_DETAILS	VALVE_TYPE	EQ_MANUFACTURER	EQ_MANUFACTURE_YEAR	VALVE_MATERIAL	VALVE_MATERIAL_DETAILS	EQ_FAILURE_DETAILS	OPERATION_TYPE	OPERATION_DETAILS	RELATED_INADEQUATE_PROC_IND	RELATED_NO_PROC_IND	RELATED_FAILURE_FOLLOW_IND	RELATED_OTHER_IND	OPERATION_RELATED_DETAILS	CATEGORY_TYPE	OPERATOR_QUALIFICATION_IND	QUALIFIED_INDIVIDUALS	OTHER_TYPE	MISC_DETAILS	UNKNOWN_SUBTYPE	INCIDENT_UNKNOWN_COMMENTS	EXTRNL_COR_GALVANIC_IND	EXTRNL_COR_ATMOSPHERIC_IND	EXTRNL_COR_STRAY_CURRENT_IND	EXTRNL_COR_MICROBIOLOGIC_IND	EXTRNL_COR_SELECTIVE_SEAM_IND	INTRNL_COR_CORROSIVE_CMDTY_IND	INTRNL_COR_WTR_DRPOUT_ACID_IND	INTRNL_COR_MICROBIOLOGIC_IND	INTRNL_COR_EROSION_IND	NF_EARTH_MOVEMENT_IND	NF_HEAVY_RAINS_IND	NF_LIGHTNING_IND	NF_TEMPERATURE_IND	NF_HIGH_WINDS_IND	NF_SNOW_ICE_IND	NF_VEGITATION_ROOT_IND	EXCVTN_DMG_OPERATOR_IND	EXCVTN_DMG_OP_CONTRACTOR_IND	EXCVTN_DMG_THIRD_PARTY_IND	EXCVTN_DMG_PREVIOUS_DAMAGE_IND	OSF_NEARBY_INDUSTRIAL_IND	OSF_VEHICLE_IND	OSF_BOAT_IND	OSF_OTHER_MARITIME_IND	OSF_ELECTRICAL_ARCING_IND	OSF_PREVOUS_MACHANICAL_IND	OSF_INTENTIONAL_IND	OSF_OTHER_UNDERGROUND_IND	PWF_DESIGN_IND	PWF_CONSTRUCTION_IND	PWF_INSTALLATION_IND	PWF_FABRICATION_IND	PWF_MANUFACTURING_IND	EQF_CONTROL_RELEAF_IND	EQF_THREADED_COUPLING_IND	EQF_NON_THREADED_IND	EQF_VALVE_FAILURE_IND	IO_DAMAGE_BY_OPERATOR_IND	IO_VALVE_POSITION_IND	IO_EQUIPMENT_OVERPRESSURE_IND	IO_NOT_INSTALLED_PROPERLY_IND	IO_WRONG_EQUIPMENT_IND	IO_INADEQUATE_PROCEDURE_IND	IO_NO_PROCEDURE_IND	IO_FOLLOW_PROCEDURE_IND	PREPARER_NAME	PREPARER_TITLE	PREPARER_EMAIL	PREPARER_TELEPHONE	PREPARER_FAX	LOCAL_CONTACT_NAME	LOCAL_CONTACT_EMAIL	LOCAL_CONTACT_TELEPHONE	AUTHORIZER_NAME	AUTHORIZER_TITLE	AUTHORIZER_TELEPHONE	AUTHORIZER_EMAIL	NARRATIVE
		// 2/26/2021	NO	YES	NO	20100001	15047	3/11/2010	SUPPLEMENTAL FINAL	15007	PACIFIC GAS & ELECTRIC CO	PG&E - GAS OPERATIONS, REGULATORY COMPLIANCE 6111 BOLLINGER CANYON RD., 	SAN RAMON	CA	94583	2/13/2010 23:35			2010	1617 EAST 9TH STREET	STOCKTON	SAN JOAQUIN	CA	95201	37.93188	-121.26133	931232											2/14/2010 1:40	NATURAL GAS		10		NO						0	NO						0	YES					NO	0	2/14/2010 0:05				2/14/2010 0:20	NO	PRIVATE PROPERTY	ABOVEGROUND	TYPICAL ABOVEGROUND FACILITY PIPING OR APPURTENANCE (E.G. VALUE OR REGULATOR STATION, OUTDOOR METER SET)				NO												PRIVATELY OWNED		OUTSIDE METER/REGULATOR SET		UNKNOWN									OTHER	ALUMINUN										OTHER									SECONDARY IGNITION	CLASS 3 LOCATION	100000	119341.09332779	500	596.705466638953	2000	2386.82186655581	0	0			0	0		0	102500	56150.2286426938	122324.620660985	0	0	1					1	1	1			PRESSURE DID NOT EXCEED MAOP					NO					NOTIFICATION FROM EMERGENCY RESPONDER			NO, THE FACILITY WAS NOT MONITORED BY A CONTROLLER(S) AT THE TIME OF THE INCIDENT														NO			NO			OTHER OUTSIDE FORCE DAMAGE	OTHER OUTSIDE FORCE DAMAGE	OTHER OUTSIDE FORCE DAMAGE	OTHER OUTSIDE FORCE DAMAGE																																																																																																																OTHER OUTSIDE FORCE DAMAGE														FIRE FIRST																																																																																																																																																			LAURENCE DENISTON	SR. PROGRAM MANAGER	lcd1@pge.com	925.974.4313					GLEN CARTER			No Email Address	A FIRE AT AN UNOCCUPIED HOME OCCURRED AT APPROXIMATELY 2335 HOURS ON 2/13/10.   THE FIRE DEPARTMENT CALLED AT PG&E AT APPROXIMATELY 0005 HOURS. THE PG&E GAS SERVICE REPRESENTATIVE (GSR) ARRIVED AT 0020 HOURS.  THE FIRE DEPARTMENT AND GSR WERE UNABLE TO SHUT OFF THE SERVICE VALVE AT THE METER DUE TO DAMAGE TO THE VALVE BY THE FIRE.  A GAS CREW WAS CALLED AND THEY CUT OFF THE GAS SERVICE AT THE MAIN AT APPROXIMATELY 02:30.  ACCORDING TO THE FIRE DEPARTMENT THE THE FIRE APPEARS TO HAVE STARTED IN ONE OF THE CLOSETS IN THE HOME.  THE HOUSE FIRE DAMAGED THE GAS METER WHICH RELEASED NATURAL GAS RESULTING IN A SECONDARY IGNITION.  THE FIRE DAMAGE TO THE HOME RESULTED IN PROPERTY DAMAGES EXCEEDING $50,000.  THERE WERE NO INJURIES AND NO FATALITIES.  NO MAJOR MEDIA WAS PRESENT.
		// 2/26/2021	NO	NO	NO	20100002	15553	3/12/2010	SUPPLEMENTAL FINAL	13730	NORTHERN INDIANA PUBLIC SERVICE CO	801 E 86TH AVENUE 	MERRILLVILLE	IN	46410	2/16/2010 10:38			2010	3835 SANDPIPER COVE RUN	SOUTH BEND	ST. JOSEPH	IN	46628	41.72931	-86.27531	931402											2/16/2010 13:45	NATURAL GAS		310		NO						0	NO						0	YES					YES	20	2/16/2010 10:38				2/16/2010 11:18	NO	PRIVATE PROPERTY	UNDERGROUND	OTHER	UNDER SOIL MIGRATED TO HOUSE	48		NO												PRIVATELY OWNED		MAIN		1990						3	ASTM D2513	PLEXCO	PLASTIC					POLYETHYLENE (PE)		11.5			2406	MECHANICAL PUNCTURE	3	1								CLASS 3 LOCATION	40000	47736.4373311162	5000	5967.05466638952	10000	11934.109332779	0	0			2500	1541.26213592233		0	57500	31727.2874191359	67178.8634662071	0	0	64					45	45	60			PRESSURE DID NOT EXCEED MAOP					NO					NOTIFICATION FROM THIRD PARTY THAT CAUSED THE INCIDENT			NO, THE FACILITY WAS NOT MONITORED BY A CONTROLLER(S) AT THE TIME OF THE INCIDENT														NO			NO			EXCAVATION DAMAGE	EXCAVATION DAMAGE BY THIRD PARTY	EXCAVATION DAMAGE	THIRD PARTY EXCAVATION DAMAGE																																																																					EXCAVATION DAMAGE BY THIRD PARTY					NO										YES	YES	CITY STREET										CONTRACTOR	BORING	ELECTRIC	NO			CONTRACT LOCATOR	YES	YES	YES	13	EXCAVATION PRACTICES NOT SUFFICIENT				FAILURE TO MAINTAIN CLEARANCE																																																																																																																																																																		JOHN CURTIS	MANAGER SYSTEM INTEGRITY AND DESIGN	jlcurtis@nisource.com	219-962-0425	219-962-0404				JOHN CURTIS	MANAGER SYSTEM INTEGRITY AND DESIGN	219-962-0425	jlcurtis@nisource.com	CONTRACTOR BORING ELECTRIC LINE PARALLEL TO 3" DISTRIBUTION LINE AT 45 PSI.  HIT LINE, WHILE TAKING PRECAUTIONS TO SHUT DOWN SYSTEM, GAS MIGRATED TO NEARBY HOUSE AND EXPLODED.    THERE WAS A REQUEST BY PHMSA THROUGH THE INDIANA PUBLIC SERVICE COMMISSION TO PROVIDE ADDTIONAL INFORMATION, AND/OR UPDATE SOME DATA FIELDS.  ALL WERE COMPLETED AS REQUESTED EXCEPT PART G REQUESTING TO COMPLETE THE SECTION FOR PREVIOUS DAMAGE DUE TO EXCAVATION.  THERE WAS NO PREVIOUS DAMAGE DUE TO EXCAVATION RELATED TO THIS INCIDENT.  THE INFORMATION FOR THE ITEMS REQUESTED IS:  1.  DATE OF MOST RECENT LEAK SURVEY CONDUCTED - ANSWER IS 3-11-2010.  2.  HAS ONE OR MORE PRESSURE TEST BEEN COMPLETED SINCE ORIGINAL CONSTRUCTION AT THE POINT OF INCIDENT - ANSWER IS NONE.    WITH ALL OF THE REQUESTED INFORMATION UPDATED THIS INCIDENT WILL BE CLOSED.
		// 2/26/2021	NO	NO	NO	20100003	15023	3/15/2010	SUPPLEMENTAL FINAL	31840	UNISOURCE ENERGY SERVICES	2901 W. SHAMRELL BLVD.	FLAGSTAFF	AZ	86001	2/22/2010 20:57			2010	8725 COUNTRY CLUB DRIVE	PINETOP	NAVAJO	AZ	85935	34.10934	-109.8601	931971											2/22/2010 22:22	NATURAL GAS		14		NO						0	NO						0	YES					NO		2/22/2010 20:57				2/22/2010 21:50	NO	PRIVATE PROPERTY	ABOVEGROUND	TYPICAL ABOVEGROUND FACILITY PIPING OR APPURTENANCE (E.G. VALUE OR REGULATOR STATION, OUTDOOR METER SET)				NO												PRIVATELY OWNED		SERVICE RISER		1999									STEEL		OTHER	ERW	0.113							LEAK			CRACK							CLASS 3 LOCATION	0	0	153	182.591872791519	2420	2888.05445853253		0			75	46.2378640776699		0	2648	1457.44458391268	3116.88419540172	0	0	1					50	55	60			PRESSURE DID NOT EXCEED MAOP					NO					NOTIFICATION FROM EMERGENCY RESPONDER			NO, THE FACILITY WAS NOT MONITORED BY A CONTROLLER(S) AT THE TIME OF THE INCIDENT														NO			NO			NATURAL FORCE DAMAGE	OTHER NATURAL FORCE DAMAGE	NATURAL FORCE DAMAGE	OTHER NATURAL FORCE DAMAGE																																																									OTHER NATURAL FORCE DAMAGE					SNOW ACCUMULATION ON THE METER SET ASSEMBLY	NO																																																																																																																																																																																																																		ROBERT ADAMS	SHOW LOW DISTRICT MANAGER	radams@uesaz.com	928 532-3801	928 537-3994				ROBERT ADAMS	SHOW LOW DISTRICT MANAGER	928 532-3801	radams@uesaz.com	ON 2/22/10 PINETOP FIRE DEPARTMENT RESPONDED TO A FIRE @ 8725 COUNTRY CLUB DRIVE AND NOTIFIED UNISOURCE ENERGY SERVICES THAT THE FIRE WAS AT THE GAS METER AND APPEARED TO INVOLVE ESCAPING GAS.  UPON ARRIVAL IT WAS DETERMINED THAT THE METER SET ASSEMBLY HAD BEEN DAMAGED; GAS WAS ESCAPING, AND HAD IGNITED. THE SERVICE LINE WAS DISCONNECTED.  THIS ACTION EXTINGUISHED THE GAS FIRE. THE FIRE DEPARTMENT EXTINGUISHED A SMALL AREA OF THE ADJACENT STRUCTURE THAT HAD CAUGHT FIRE.   TTHE PROBABLE CAUSE FOR THE DAMAGE TO THE METER SET ASSEMBLY WAS THE FORCE EXERTED UPON IT BY SIX PLUS FEET OF SNOW AND ICE THAT HAD ACCUMULATED AND FALLEN FROM THE ROOF OF THE ADJACENT STRUCTURE.  ON 2/23/10 THE AFFECTED RISER WAS REPLACED THE SERVICE LINE TESTED AND RECONNECTED BY UES CONSTRUCTION PERSONNEL.     ON 4/14/10, A SUPPLIMENTAL FILE WAS UPDATED WITH CORRECTED 14 MCF OF LOST GAS AND $0. ESTIMATED COST FOR PUBLIC AND NON OPERATOR PRIVATE PROPERTY DAMAGE PAID/REINBURSED BY THE OPERATOR. AN UPDATED TOTAL FOR THE ESTIMATED COST TO THE OPERATOR IS $2,648.    ON 5/5/10, A SUPPLIMENTAL FILE WAS UPDATED WITH THIS ADDITIONAL INFORMATION BASED ON A CONVERSATION WITH ANGELA DOW OF PHMSA ON 5/5/10. THE COST OF REPAIRS, AS PROVIDED BY THE CONTRACTOR PERFORMING THE WORK TO THE STRUCTURE ARE $25,000.THESE COSTS ARE BEING COVERED BY PARTIES OTHER THAN THE OPERATOR.
		if (fgets (buffer, 16384, f)) {

			while (fgets (buffer, 16384, f)) {
				data = buffer;
				data.tokenize (",", &tokens, true, false);

				if (tokens.size () == 472) {
					leak = gas_distribution->create_new (MAP_OBJECT_POINT);
					leak->id = atol (tokens [4].get_text_ascii ()); // REPORT_NUMBER
					leak->attributes_numeric [0]  = atol (tokens [8].get_text_ascii ()); // Operator_ID
					leak->attributes_text [0] = tokens[14]; // Local_DateTime

					if (tokens [23].get_length () > 0)
						leak->latitude = (long) (atof (tokens [23].get_text_ascii ()) * 1.0e6); // Location_Latitude 
					if (tokens [24].get_length () > 0)
						leak->longitude = (long) (atof (tokens [24].get_text_ascii ()) * 1.0e6); // Location_Longitude
					if (tokens [39].get_length () > 0)
						leak->attributes_numeric [1] = atof (tokens [39].get_text_ascii ()); // UNINTENTIONAL_RELEASE_BBLS
					gas_distribution->objects.push_back (leak);
				}
				else {
					log += "ERROR, unable to parse gas distribution data \"";
					log += buffer;
					log += "\"\n";
				}
			}
		}

		fclose (f);
		return true;
	}
	else {
		log += "ERROR, can't open Pipeline file \"";
		log += filename;
		log += "\".\n";
		return false;
	}
}

bool PipelineAccidents::read_gas_gathering
	(dynamic_string &filename,
	interface_window *view,
	dynamic_string &log)

{
	FILE *f;
	dynamic_string data;
	char buffer[16384];
	map_object *leak;
	std::vector <dynamic_string> tokens;

	view->update_progress (filename, 1);

	if (fopen_s (&f, filename.get_text_ascii (), "r") == 0) {
		// DATAFILE_AS_OF	SIGNIFICANT	SERIOUS	SYSTEM_TYPE	REPORT_NUMBER	SUPPLEMENTAL_NUMBER	REPORT_RECEIVED_DATE	REPORT_TYPE	OPERATOR_ID	NAME	OPERATOR_STREET_ADDRESS	OPERATOR_CITY_NAME	OPERATOR_STATE_ABBREVIATION	OPERATOR_POSTAL_CODE	LOCAL_DATETIME	IYEAR	TIME_ZONE	DAYLIGHT_SAVINGS_IND	LOCATION_LATITUDE	LOCATION_LONGITUDE	NRC_RPT_NUM	NRC_RPT_DATETIME	ADDITIONAL_NRC_REPORT_NUMBERS	COMMODITY_RELEASED_TYPE	COMMODITY_DETAILS	UNINTENTIONAL_RELEASE	INTENTIONAL_RELEASE	ACCOMPANYING_LIQUID	FATALITY_IND	NUM_EMP_FATALITIES	NUM_CONTR_FATALITIES	NUM_ER_FATALITIES	NUM_WORKER_FATALITIES	NUM_GP_FATALITIES	FATAL	INJURY_IND	NUM_EMP_INJURIES	NUM_CONTR_INJURIES	NUM_ER_INJURIES	NUM_WORKER_INJURIES	NUM_GP_INJURIES	INJURE	STATUS_WHEN_IDENTIFIED	SHUTDOWN_DUE_ACCIDENT_IND	SHUTDOWN_EXPLAIN	SHUTDOWN_DATETIME	RESTART_DATETIME	STILL_SHUTDOWN_IND	COMMUNICATION_STATE_FED_IND	PARTY_INITIATED_COMMUNICATION	INITIAL_RESPONDER_COM_DATETIME	IGNITE_IND	IGNITE_DATETIME	HOW_EXTINGUISHED	HOW_EXTINGUISHED_OTHER_DETAIL	GAS_CONSUMED_BY_FIRE_IN_MCF	EXPLODE_IND	UPSTREAM_ACTION_TAKEN	UPSTREAM_OPRTNL_CNTRL_DETAIL	UPSTREAM_VALVE_CLOSE_DATETIME	DOWNSTREAM_ACTION_TAKEN	DOWNSTREAM_OPRTNL_CNTRL_DETAIL	DOWNSTREAM_VLV_CLOSE_DATETIME	NUM_PUB_EVACUATED	INCIDENT_IDENTIFIED_DATETIME	ON_SITE_DATETIME	ON_OFF_SHORE	ONSHORE_STATE_ABBREVIATION	ONSHORE_POSTAL_CODE	ONSHORE_CITY_NAME	ONSHORE_COUNTY_NAME	DESIGNATED_LOCATION	DESIGNATED_NAME	PIPE_FAC_NAME	SEGMENT_NAME	FEDERAL	LOCATION_TYPE	INCIDENT_AREA_TYPE	INCIDENT_AREA_SUBTYPE	INCIDENT_AREA_DETAILS	DEPTH_OF_COVER	OTHER_UNDERGROUND_FACILITIES	CROSSING	BRIDGE_CROSSING_IND	BRIDGE_TYPE	RAILROAD_CROSSING_IND	RAILROAD_TYPE	ROAD_CROSSING_IND	ROAD_TYPE	WATER_CROSSING_IND	WATER_TYPE	WATER_NAME	WATER_DEPTH	WATER_SUBTYPE	CROSSING_100_FEET	OFF_WATER_DEPTH	OFF_ACCIDENT_ORIGIN	OFFSHORE_STATE_ABBREVIATION	OFF_INSTATE_AREA	OFF_INSTATE_BLOCK	OFFSHORE_COUNTY_NAME	OCS_TYPE	OFF_OCS_AREA	OFF_OCS_BLOCK	OFF_AREA_ACCIDENT_TYPE	PIPE_FACILITY_TYPE	SYSTEM_PART_INVOLVED	ITEM_INVOLVED	PIPE_TYPE	PIPE_DIAMETER	PUDDLE_WELD_IND	PIPE_WALL_THICKNESS	PIPE_SMYS	PIPE_SPECIFICATION	PIPE_SEAM_TYPE	PIPE_SEAM_DETAILS	PIPE_MANUFACTURER	PIPE_COATING_TYPE	PIPE_COATING_DETAILS	COATING_APPLIED_IND	PLASTIC_TYPE	PLASTIC_DETAILS	PLASTIC_SDR	WT_PLASTIC	WT_PLASTIC_UNKNOWN_IND	MATERIAL_PE_PIPE_CODE	PLASTIC_PE_UNKNOWN_IND	WELD_SUBTYPE	WELD_DETAILS	DIFFERENT_GIRTH_WELD_IND	DIFF_GIRTH_WELD_WALL_THICKNESS	DIFF_GIRTH_WELD_SMYS	DIFF_GIRTH_WELD_SPECIFICATION	DIFF_GIRTH_WELD_SEAM_TYPE	DIFF_GIRTH_WELD_SEAM_DETAIL	DIFF_GIRTH_WELD_MANUFACTURER	DIFF_GIRTH_WELD_COATING_TYPE	DIFF_GIRTH_WELD_COATING_DETAIL	DIFF_GIRTH_WELD_CTNG_APPLD_IND	VALVE_TYPE	VALVE_MAINLINE_TYPE	VALVE_MAINLINE_DETAILS	VALVE_MANUFACTURER	TUBING_MATERIAL	TUBING_TYPE	ITEM_INVOLVED_DETAILS	INSTALLATION_YEAR	MANUFACTURED_YEAR	MATERIAL_INVOLVED	MATERIAL_DETAILS	RELEASE_TYPE	PUNCTURE_AXIAL	PUNCTURE_CIRCUM	LEAK_TYPE	LEAK_TYPE_OTHER	RUPTURE_ORIENT	RUPTURE_DETAILS	RUPTURE_LENGTH	RUPTURE_WIDTH	RELEASE_TYPE_DETAILS	CLASS_LOCATION_TYPE	COULD_BE_HCA	DETERMINATION_METHOD	PIR_RADIUS	NOT_FLAMMABLE_IND	HEAT_DAMAGE_IND	NON_HEAT_DAMAGE_IND	HCA_FATALITIES_IND	FATAL_INJURE_CAUSE	EST_COST_OPER_PAID	EST_COST_OPER_PAID_CURRENT	EST_COST_INTENT_REL	EST_COST_INTENT_REL_CURRENT	EST_COST_GAS_RELEASED	EST_COST_GAS_RELEASED_CURRENT	EST_COST_PROP_DAMAGE	EST_COST_PROP_DAMAGE_CURRENT	EST_COST_EMERGENCY	EST_COST_EMERGENCY_CURRENT	EST_COST_OTHER	EST_COST_OTHER_CURRENT	EST_COST_OTHER_DETAILS	GAS_COST_IN_MCF	TOTAL_COST	TOTAL_COST_IN84	TOTAL_COST_CURRENT	NUM_PERSONS_HOSP_NOT_OVNGHT	NUM_INJURED_TREATED_BY_EMT	NUM_RESIDENT_BUILDING_AFFCTD	NUM_BUSINESS_BUILDING_AFFCTD	WILDLIFE_IMPACT_IND	FISH_AQUATIC_IMPACT_IND	BIRDS_IMPACT_IND	TERRESTRIAL_IMPACT_IND	ACCIDENT_PSIG	GAS_FLOW_IN_PIPE_IN_MCF	MOP_PSIG	MOP_CFR_SECTION	MOP_CFR_SECTION_DETAILS	MAOP_ESTABLISHED_DATE	MAOP_REVERSAL_FLOW_IND	ACCIDENT_PRESSURE	PRESSURE_RESTRICTION_IND	EXCEED_RESTRICTION_IND	PHMSA_RESTRICTION_IND	GAS_REQUIRED_ODORIZED_IND	GAS_ODORIZED_IND	UPSTREAM_VALVE_TYPE_IND	DOWNSTREAM_VALVE_TYPE_IND	LENGTH_SEGMENT_ISOLATED	INTERNAL_INSPECTION_IND	DIAMETER_CHANGE_IND	UNSUITABLE_MAINLINE_IND	TIGHT_MITERED_IND	OTHER_RESTRICTIONS_IND	EXTRA_THICK_WALL_IND	OTHER_INSPECTION_IND	INTERNAL_INSPECTION_DETAILS	OPERATION_COMPLICATIONS_IND	EXCESSIVE_DEBRIS_IND	LOW_OP_PRESSURE_IND	LOW_FLOW_IND	INCOMPAT_COMMOD_IND	OTHER_COMPLICATIONS_IND	INSPECT_COMP_DETAILS	PIPELINE_FUNCTION	SCADA_IN_PLACE_IND	SCADA_OPERATING_IND	SCADA_FUNCTIONAL_IND	SCADA_DETECTION_IND	SCADA_CONF_IND	ACCIDENT_IDENTIFIER	ACCIDENT_DETAILS	OPERATOR_TYPE	INVESTIGATION_STATUS	INVESTIGATION_STATUS_DETAILS	INVEST_SCHEDULE_IND	INVEST_NO_SCHEDULE_IND	INVEST_NO_SCHEDULE_IND_DETAILS	INVEST_NO_CONTROL_ROOM_IND	INVEST_NO_CONTROLLER_IND	INVEST_INCORRECT_ACTION_IND	INVEST_FATIGUE_IND	INVEST_INCORRECT_PROCEDURE_IND	INVEST_INCORRECT_CONTROL_IND	INVEST_MAINT_IND	INVEST_OTHER_IND	INVEST_OTHER_IND_DETAILS	EMPLOYEE_DRUG_TEST_IND	NUM_EMPLOYEES_TESTED	NUM_EMPLOYEES_FAILED	CONTRACTOR_DRUG_TEST_IND	NUM_CONTRACTORS_TESTED	NUM_CONTRACTORS_FAILED	CAUSE	CAUSE_DETAILS	MAP_CAUSE	MAP_SUBCAUSE	INTERNAL_EXTERNAL	VISUAL_EXAM_RESULTS	VISUAL_EXAM_DETAILS	GALVANIC_CORROSION_IND	ATMOSPHERE_CORROSION_IND	STRAY_CURRENT_CORROSION_IND	MICROBIOLOGICAL_CORROSION_IND	SELECTIVE_SEAM_CORROSION_IND	OTHER_CORROSION_IND	CORROSION_TYPE_DETAILS	STRAY_CURRENT_TYPE	STRAY_CURRENT_DETAILS	FIELD_EXAM_BASIS_IND	METALLURGICAL_BASIS_IND	OTHER_BASIS_IND	CORROSION_BASIS_DETAILS	UNDERGROUND_LOCATION	UNDER_CATHODIC_PROTECTION_IND	CATHODIC_PRO_START_YEAR	SHIELDING_EVIDENT	CATHODIC_SURVEY_TYPE	CP_ANNUAL_SURVEY_IND	CLOSE_INTERVAL_SURVEY_IND	OTHER_CP_SURVEY_IND	OTHER_CP_SURVEY_DETAILS	CP_ANNUAL_SURVEY_YEAR	CLOSE_INTERVAL_SURVEY_YEAR	OTHER_CP_SURVEY_YEAR	EXTERNALLY_COATED	PRIOR_DAMAGE	INT_VISUAL_EXAM_RESULTS	INT_VISUAL_EXAM_DETAILS	INT_CORROSIVE_COMMODITY_IND	INT_WATER_ACID_IND	INT_MICROBIOLOGICAL_IND	INT_EROSION_IND	INT_OTHER_CORROSION_IND	INT_CORROSION_TYPE_DETAILS	INT_FIELD_EXAM_BASIS_IND	INT_METALLURGICAL_BASIS_IND	INT_OTHER_BASIS_IND	INT_CORROSION_BASIS_DETAILS	INT_LOW_POINT_PIPE_LOC_IND	INT_ELBOW_LOC_IND	INT_DROP_OUT_LOC_IND	INT_DEAD_LEG_LOC_IND	INT_OTHER_LOC_IND	CORROSION_LOCATION_DETAILS	CORROSION_INHIBITORS	CORROSION_LINING	CLEANING_DEWATERING	CORROSION_COUPONS	NATURAL_FORCE_TYPE	EARTH_SUBTYPE	HEAVY_RAINS_SUBTYPE	LIGHTNING_SUBTYPE	TEMPERATURE_SUBTYPE	NF_OTHER_DETAILS	NF_EXTREME_WEATHER_IND	NF_HURRICANE_IND	NF_TROPICAL_STORM_IND	NF_TORNADO_IND	NF_OTHER_IND	NF_EXTREME_WEATHER_DETAILS	PARTY_TYPE	PRIOR_NOTIFICATION_IND	ONE_CALL_SYSTEM_IND	EXCAVATOR_IND	CONTRACTOR_IND	LANDOWNER_IND	STATE_LAW_EXEMPT_IND	STATE_LAW_EXEMPT_TYPE	STATE_LAW_EXEMPT_DETAIL	STATE_LAW_EXEMPT_AUTHORITY	STATE_LAW_EXEMPT_CRITERIA	NOTIFY_CGA_DIRT	PUBLIC_ROW_IND	PUBLIC_SUBTYPE	PRIVATE_ROW_IND	PRIVATE_SUBTYPE	PIPELINE_EASEMENT_ROW_IND	POWER_TRANSMISSION_ROW_IND	RAILROAD_ROW_IND	PUBLIC_UTIL_EASEMENT_ROW_IND	FEDERAL_LAND_ROW_IND	DATA_NOT_COLLECTED_ROW_IND	UNKNOWN_ROW_IND	EXCAVATOR_TYPE	EXCAVATOR_EQUIPMENT	WORK_PERFORMED	ONE_CALL_NOTIFIED_IND	ONE_CALL_TICKET_NUM	ONE_CALL_CENTER_NAME	LOCATOR_TYPE	VISIBLE_MARKS	FACILITIES_MARKED	SERVICE_INTERRUPTION	SERVICE_INTERRUPTION_HOURS	ROOT_CAUSE	ONE_CALL_SUBTYPE	LOCATING_SUBTYPE	EXCAVATION_SUBTYPE	ROOT_CAUSE_OTHER	OUTSIDE_FORCE_TYPE	VEHICLE_SUBTYPE	OSF_HURRICANE_IND	OSF_TROPICAL_STORM_IND	OSF_TORNADO_IND	OSF_HEAVY_RAINS_IND	OSF_OTHER_WEATHER_IND	OSF_OTHER_WEATHER_DETAILS	INTENTIONAL_SUBTYPE	INTENTIONAL_DETAILS	OSF_OTHER_DETAILS	DRIVER_ISSUED_CITATION_IND	CITATION_SPEED_IND	CITATION_RECKLESS_IND	CITATION_DUI_IND	CITATION_OTHER_IND	CITATION_OTHER_DETAIL	DRIVER_IN_CONTROL_IND	ESTIMATED_SPEED	ESTIMATED_SPEED_UNKNOWN_IND	VEHICLE_TYPE	VEHICLE_TRAVEL_FROM	VEHICLE_TRAVEL_DISTANCE_FT	PROTECTIONS_INSTALLED_IND	PROTECTION_BOLLARDS_POST_IND	PROTECTION_BARRICADES_IND	PROTECTION_GUARD_RAILS_IND	PROTECTION_OTHER_IND	PROTECTION_OTHER_DETAIL	PWJF_FAILURE_TYPE	FIELD_EXAM_IND	METALLURGICAL_IND	OTHER_ANALYSIS_IND	OTHER_ANALYSIS_DETAILS	STILL_UNDER_INVEST_IND	FATIGUE_VIBR_RELATED_1	FAILURE_SUBTYPE_1	FATIGUE_VIBR_RELATED_OTHER_1	MECHANICAL_STRESS_1	OTHER_FACTOR_1	OTHER_FACTOR_DETAILS_1	FATIGUE_VIBR_RELATED_2	FAILURE_SUBTYPE_2	FATIGUE_VIBR_RELATED_OTHER_2	MECHANICAL_STRESS_2	OTHER_FACTOR_2	OTHER_FACTOR_DETAILS_2	STRESS_SUBTYPE	STRESS_DETAILS	ADDITIONAL_DENT_IND	ADDITIONAL_GOUGE_IND	ADDITIONAL_PIPE_BEND_IND	ADDITIONAL_ARC_BURN_IND	ADDITIONAL_CRACK_IND	ADDITIONAL_LACK_FUSION_IND	ADDITIONAL_LAMINATION_IND	ADDITIONAL_BUCKLE_IND	ADDITIONAL_WRINKLE_IND	PWF_ADDITIONAL_MISALIGN_IND	ADDITIONAL_BURNT_STEEL_IND	PWF_ADDITIONAL_OTHER_IND	ADDITIONAL_OTHER_DETAILS	POST_CONSTR_PRESSURE_TEST_VAL	EQ_FAILURE_TYPE	CONTROL_VALVE_IND	INSTRUMENTATION_IND	SCADA_IND	COMMUNICATIONS_IND	BLOCK_VALVE_IND	CHECK_VALVE_IND	RELIEF_VALVE_IND	POWER_FAILURE_IND	STOPPLE_CONTROL_FITTING_IND	PRESSURE_REGULATOR_IND	ESD_SYSTEM_FAILURE_IND	OTHER_CONTROL_RELIEF_IND	OTHER_CONTROL_RELIEF_DETAILS	OTHER_PUMP_IND	OTHER_PUMP_DETAILS	OTHER_STRIPPED_IND	OTHER_STRIPPED_DETAILS	OTHER_NON_THREADED_IND	OTHER_NON_THREADED_DETAILS	EQ_FAILURE_DETAILS	ADDITIONAL_VIBRATION_IND	ADDITIONAL_OVERPRESSURE_IND	ADDITIONAL_SUPPORT_IND	ADDITIONAL_DEFECT_IND	ADDITIONAL_ELECTRICITY_IND	ADDITIONAL_INSTALLATION_IND	ADDITIONAL_IMPROPER_MNTNCE_IND	ADDITIONAL_MISMATCH_IND	ADDITIONAL_DISSIMILAR_IND	ADDITIONAL_BREAKDOWN_IND	ADDITIONAL_VALVE_IND	ADDITIONAL_ALARM_IND	EQ_ADDITIONAL_MISALIGN_IND	EQ_ADDITIONAL_THERMAL_IND	ADDITIONAL_EROSION_WEAR_IND	EQ_ADDITIONAL_OTHER_IND	EQ_ADDITIONAL_OTHER_DETAILS	OPERATION_TYPE	OVERFLOW_OTHER_IND	OVERFLOW_OTHER_DETAILS	OPERATION_DETAILS	RELATED_INADEQUATE_PROC_IND	RELATED_NO_PROC_IND	RELATED_FAILURE_FOLLOW_IND	RELATED_OTHER_IND	OPERATION_RELATED_DETAILS	CATEGORY_TYPE	OPERATOR_QUALIFICATION_IND	QUALIFIED_INDIVIDUALS	OTHER_TYPE	MISC_DETAILS	UNKNOWN_SUBTYPE	INCIDENT_UNKNOWN_COMMENTS	COLLECTED_DATA_IND	AXIAL_MAGNETIC_FLX_LKG_IND	CIR_TRN_WAVE_MGN_FLX_LKG_IND	ULTRASONIC_IND	GEOMETRY_DEFORMATION_IND	EMAT_IND	CPCM_IND	OTHER_TOOL_TECH_IND	AXIAL_RECENT_YEAR	AXIAL_RCNT_PROPUL_METHOD	AXIAL_RCNT_ATTUNED_DETECT	AXIAL_RCNT_ATND_DTCT_DTLS	AXIAL_RCNT_ATND_DTCT_METAL	AXIAL_RCNT_ATT_DT_METAL_DTLS	AXIAL_PREVIOUS_YEAR	AXIAL_PREV_PROPUL_METHOD	AXIAL_PREV_ATTUNED_DETECT	AXIAL_PREV_ATND_DTCT_DTLS	AXIAL_PREV_ATND_DTCT_METAL	AXIAL_PREV_ATT_DT_METAL_DTLS	CIRC_WAVE_RECENT_YEAR	CIRC_WV_RCNT_PROPUL_METHOD	CIRC_WV_RCNT_RESOLUTION	CIRC_WV_RCNT_RESOLUTION_DTLS	CIRC_WV_PREVIOUS_YEAR	CIRC_WV_PREV_PROPUL_METHOD	CIRC_WV_PREV_RESOLUTION	CIRC_WV_PREV_RESOLUTION_DTLS	ULTRASONIC_RECENT_YEAR	ULTRASONIC_RCNT_PROPUL_METHOD	ULTRASONIC_RCNT_ATTUNED	ULTRA_RCNT_ATTUNEDD_DTLS	UTRA_RCNT_ATT_METL_RESOLUTION	UTRA_RCNT_ATT_METL_RES_DTLS	ULTR_PREVIOUS_YEAR	ULTRA_PREV_PROPUL_METHOD	ULTRA_PREV_ATTUNED	ULTRA_PREV_ATTUNED_DTLS	UTRA_PREV_ATT_METL_RESOLUTION	UTRA_PREV_ATT_METL_RES_DTLS	GEOMETRY_RECENT_YEAR	GEOMETRY_RCNT_PROPUL_METHOD	GEOMETRY_RCNT_RESOLUTION	GEOMETRY_RCNT_RESOLUTION_DTLS	GEOMETRT_RCNT_MEASUR_CUPS	GEOMETRY_PREVIOUS_YEAR	GEOMETRY_PREV_PROPUL_METHOD	GEOMETRY_PREV_RESOLUTION	GEOMETRY_PREV_RESOLUTION_DTLS	GEOMETRT_PREV_MEASUR_CUPS	EMAT_RECENT_YEAR	EMAT_RCNT_PROPUL_METHOD	EMAT_PREVIOUS_YEAR	EMAT_PREV_PROPUL_METHOD	CPCM_RECENT_YEAR	CPCM_RCNT_PROPUL_METHOD	CPCM_PREVIOUS_YEAR	CPCM_PREV_PROPUL_METHOD	OTHER_TOOL	OTHER_RECENT_YEAR	OTHER_RCNT_PROPUL_METHOD	OTHER_PREVIOUS_YEAR	OTHER_PREV_PROPUL_METHOD	INSP_COMPL_BEFORE_DAMAGE_IND	HAS_HYDRTST_CONDUC_BEFORE_IND	HYDRTST_MOST_RCNT_YEAR	HYDRTST_MOST_RCNT_PRESSURE	DIRECT_ASMNT_CONDUCTED	DIRECT_ASMNT_AT_PNT_ACCDNT_YR	DIRECT_ASMNT_PNT_NOT_IDNTF_YR	ASMNT_ECDA_RCNT_YEAR	ASMNT_ICDA_RCNT_YEAR	ASMNT_SCCDA_RCNT_YEAR	ASMNT_CONFIRMATORY_RCNT_YEAR	ASMNT_OTHER_TYPE	ASMNT_OTHER_RCNT_YEAR	ASMNT_ECDA_RCNT_IND	ASMNT_ICDA_RCNT_IND	ASMNT_SCCDA_RCNT_IND	ASMNT_CONFIRMATORY_RCNT_IND	ASMNT_OTHER_RCNT_IND	NON_DESTRUCTIVE_EXAM_IND	EXM_RADIOGRAPHY_RCNT_YEAR	EXM_WAVE_ULTRASONIC_RCNT_YEAR	EXM_HANDL_ULTRASONIC_RCNT_YEAR	EXM_WET_MGNT_PARTCL_RCNT_YEAR	EXM_DRY_MGNT_PARTCL_RCNT_YEAR	EXM_OTHER_TYPE	EXM_OTHER_RCNT_YEAR	EXM_RADIOGRAPHY_RCNT_IND	EXM_WAVE_ULTRASONIC_RCNT_IND	EXM_HANDL_ULTRASONIC_RCNT_IND	EXM_WET_MGNT_PARTCL_RCNT_IND	EXM_DRY_MGNT_PARTCL_RCNT_IND	EXM_OTHER_RCNT_IND	EXTRNL_COR_GALVANIC_IND	EXTRNL_COR_ATMOSPHERIC_IND	EXTRNL_COR_STRAY_CURRENT_IND	EXTRNL_COR_MICROBIOLOGIC_IND	EXTRNL_COR_SELECTIVE_SEAM_IND	INTRNL_COR_CORROSIVE_CMDTY_IND	INTRNL_COR_WTR_DRPOUT_ACID_IND	INTRNL_COR_MICROBIOLOGIC_IND	INTRNL_COR_EROSION_IND	NF_EARTH_MOVEMENT_IND	NF_HEAVY_RAINS_IND	NF_LIGHTNING_IND	NF_TEMPERATURE_IND	NF_HIGH_WINDS_IND	NF_VEGITATION_ROOT_IND	EXCVTN_DMG_OPERATOR_IND	EXCVTN_DMG_OP_CONTRACTOR_IND	EXCVTN_DMG_THIRD_PARTY_IND	EXCVTN_DMG_PREVIOUS_DAMAGE_IND	OSF_NEARBY_INDUSTRIAL_IND	OSF_VEHICLE_IND	OSF_BOAT_IND	OSF_OTHER_MARITIME_IND	OSF_ELECTRICAL_ARCING_IND	OSF_PREVOUS_MACHANICAL_IND	OSF_INTENTIONAL_IND	OSF_OTHER_UNDERGROUND_IND	PWF_DESIGN_IND	PWF_CONSTRUCTION_IND	PWF_INSTALLATION_IND	PWF_FABRICATION_IND	PWF_MANUFACTURING_IND	PWF_ENV_STRESS_CORROSION_IND	PWF_ENV_SULFIDE_STRESS_IND	PWF_ENV_HYDROGEN_STRESS_IND	PWF_ENV_HARD_SPOT_IND	EQF_CONTROL_RELEAF_IND	EQF_COMPRESSOR_IND	EQF_THREADED_COUPLING_IND	EQF_NON_THREADED_IND	EQF_DEFECTIVE_FITTING_IND	EQF_EQUIPMENT_BODY_IND	IO_DAMAGE_BY_OPERATOR_IND	IO_VALVE_POSITION_IND	IO_EQUIPMENT_OVERPRESSURE_IND	IO_NOT_INSTALLED_PROPERLY_IND	IO_WRONG_EQUIPMENT_IND	IO_INADEQUATE_PROCEDURE_IND	IO_NO_PROCEDURE_IND	IO_FOLLOW_PROCEDURE_IND	PREPARER_NAME	PREPARER_TITLE	PREPARER_EMAIL	PREPARER_TELEPHONE	PREPARER_FAX	LOCAL_CONTACT_NAME	LOCAL_CONTACT_EMAIL	LOCAL_CONTACT_TELEPHONE	AUTHORIZER_NAME	AUTHORIZER_TITLE	AUTHORIZER_TELEPHONE	AUTHORIZER_EMAIL	NARRATIVE
		// 2/26/2021	YES	NO	GT (Gas Transmission)	20100001	15951	3/10/2010	SUPPLEMENTAL FINAL	602	CENTERPOINT ENERGY GAS TRANSMISSION	499 W. SHERIDAN  STE 1500	OKLAHOMA CITY	OK	73102	2/9/2010 1:32	2010			35.67235	-99.27199	930880	2/10/2010 14:08		NATURAL GAS		30142	0	0	NO						0	NO						0		NO								NO					NO							0	2/9/2010 1:32	2/9/2010 1:43	ONSHORE	OK	73650	HAMMOND	CUSTER	SURVEY STATION NO.	4515+67	CEGT AD-WEST	RED MOON CMPR ST.	NO	OPERATOR-CONTROLLED PROPERTY	ABOVEGROUND	TYPICAL ABOVEGROUND FACILITY PIPING OR APPURTENANCE				NO																							INTERSTATE	ONSHORE COMPRESSOR STATION EQUIPMENT AND PIPING	REGULATOR/CONTROL VALVE																																							1990		MATERIAL OTHER THAN CARBON STEEL OR PLASTIC	TEFLON SEAT	OTHER									REGULATOR ON PNEUMATIC ACTUATOR	CLASS 1 LOCATION	NO		524		NO	NO	NO		0	0	0	0	172714	106479.019417476	775	924.893473290376	400	477.364373311162	0	0			173889	111035.30765694	107881.277264077									855		1000	NOT ON OMB-APPROVED FORM WHEN SUBMITTED				PRESSURE DID NOT EXCEED MAOP	NO																							TRANSMISSION SYSTEM	YES	YES	YES	YES	NO	SCADA-BASED INFORMATION (SUCH AS ALARM(S), ALERT(S), EVENT(S), AND/OR VOLUME OR PACK CALCULATIONS)			NO, THE OPERATOR DID NOT FIND THAT AN INVESTIGATION OF THE CONTROLLER(S) ACTIONS OR CONTROL ROOM ISSUES WAS NECESSARY DUE TO: (PROVIDE AN EXPLANATION FOR WHY THE OPERATOR DID NOT INVESTIGATE)	NO INDICATION OF ANY ACTIONS BY CONTROL PRIOR TO THE INCIDENT													NO			NO			NATURAL FORCE DAMAGE	TEMPERATURE	NATURAL FORCE DAMAGE	TEMPERATURE																																																					TEMPERATURE				FROZEN COMPONENTS		YES				YES	ICE STORM																																																																																																																																																																																																																																																																																																														JOHNNY L. CAVITT	DOT COMPLIANCE MANAGER	johnny.cavitt@centerpointenergy.com	318-429-3606	318-429-3927				JOHNNY L. CAVITT	DOT COMPLIANCE MANAGER	318-429-3606	johnny.cavitt@centerpointenergy.com	THE REGULATOR FOR THE PNEUMATIC ACTUATOR FROZEN UP AND CAUSE PRESSURE TO DROP BELOW WHAT WAS NEEDED TO KEEP THE ACTUATOR CLOSED AND IT  FAILED OPEN RELEASING GAS THROUGH THE BLOW DOWN VALVE ON THE ESD DISCHARGE BLOWDOWN VALVE(3") ON 16" HEADERS.
		// 2/26/2021	YES	NO	GT (Gas Transmission)	20100002	15077	3/12/2010	SUPPLEMENTAL FINAL	18516	SOUTHERN NATURAL GAS CO	569 BROOKWOOD VILLAGE	BIRMINGHAM	AL	35209	1/6/2010 4:32	2010			33.10762	-89.15281	927803	1/6/2010 6:25		NATURAL GAS		41176	0	0	NO						0	NO						0		YES		1/6/2010 4:58	1/20/2010 16:16					NO					NO								1/6/2010 4:32	1/6/2010 4:44	ONSHORE	MS	39339	LOUISVILLE	WINSTON	MILEPOST	50.785	2ND NORTH MAIN	CENTER RIDGE GATE TO LOUISVILLE	NO	PIPELINE RIGHT-OF-WAY	UNDERGROUND	UNDER SOIL		60		NO																							INTERSTATE	ONSHORE PIPELINE, INCLUDING VALVE SITES	PIPE	PIPE BODY	24		0.25	52000	API 5L OR EQUIVALENT	DSAW		REPUBLIC	COAL TAR																													1952	1952	CARBON STEEL		RUPTURE					LONGITUDINAL		640	75.4		CLASS 2 LOCATION	NO		454		NO	NO	NO		4000	4773.64373311162		0	242699	149625.111650485	140000	167077.530658907	20000	23868.2186655581		0			406699	244963.513077501	345344.504708062									740		750	NOT ON OMB-APPROVED FORM WHEN SUBMITTED				PRESSURE DID NOT EXCEED MAOP	NO					MANUAL	MANUAL	54458	YES								NO							TRANSMISSION SYSTEM	YES	YES	YES	YES	YES	LOCAL OPERATING PERSONNEL, INCLUDING CONTRACTORS		OPERATOR EMPLOYEE	NO, THE OPERATOR DID NOT FIND THAT AN INVESTIGATION OF THE CONTROLLER(S) ACTIONS OR CONTROL ROOM ISSUES WAS NECESSARY DUE TO: (PROVIDE AN EXPLANATION FOR WHY THE OPERATOR DID NOT INVESTIGATE)	LOW ALARM AND PHONE CALL FROM FIELD PERSONNEL OCCURRED SIMULTANEOUSLY													NO			NO			CORROSION FAILURE	EXTERNAL CORROSION	CORROSION	EXTERNAL	EXTERNAL CORROSION	GENERAL CORROSION		YES					YES	NEAR NEUTRAL PH SCC AS SECONDARY FAILURE MECHANISM.			YES	YES			YES	YES	1963	NO	YES	YES				2009				NO																																																																																																																																																																																															YES	YES			YES				2009																																2009																								YES	1994	990	NO														NO																																																																KENNETH C PETERS	MANAGER - DOT COMPLIANCE FIELD SUPPORT	ken.peters@elpaso.com	2053257554	2053253729				KENNETH C PETERS	MANAGER - DOT COMPLIANCE FIELD SUPPORT	2053257554	ken.peters@elpaso.com	ON JANUARY 6 2010 SOUTHERN NATURAL GAS (SNG) COMPANY OPERATIONS PERSONNEL AT THE LOUISVILLE (MS) COMPRESSOR STATION ADVISED SNG GAS CONTROL THAT MEMBERS OF THE GENERAL PUBLIC HAD REPORTED A LOUD NOISE NEAR HIGHWAY 14 WEST OF LOUISVILLE MS. GAS CONTROL SAW A CORRESPONDING PRESSURE DROP VIA THE SCADA SYSTEM. A FAILURE HAD OCCURED ON SNG'S 24 INCH 2ND NORTH MAIN PIPELINE. SNG FIELD PERSONNEL WERE DISPATCHED TO CLOSE VALVES FOR ISOLATION OF THE FAILURE SITE AND TAKE THE AFFECTED SEGMENT OF PIPELINE OUT OF SERVICE. THE FAILURE WAS CAUSED BY A CLUSTER OF EXTERNAL CORROSION PITS WITH SUBSEQUENT NEAR-NEUTRAL PH STRESS CORROSION CRACKING (SCC) CONFINED WITHIN A LOCALIZED AREA OF THE MOST SEVERE CORROSION.  THE EVIDENCE GATHERED DURING THE INVESTIGATION CONCLUDED THAT THE EXTERNAL CORROSION WHICH INITIATED THIS FAILURE ALLOWED ELECTROCHEMICAL CORROSION TO THIN THE PIPE WALL, INCREASING THE LOCALIZED STRESSES, WHICH CROSSED THE THRESHOLD FOR SCC TO INITIATE AND PROPAGATE UNTIL THE REMAINING PIPE WALL COULD NO LONGER SUPPORT NORMAL OPERATING PRESSURE.
		// 2/26/2021	NO	NO	GT (Gas Transmission)	20100003	15054	3/16/2010	SUPPLEMENTAL FINAL	602	CENTERPOINT ENERGY GAS TRANSMISSION	499 W. SHERIDAN  STE 1500	OKLAHOMA CITY	OK	73102	2/16/2010 8:18	2010			35.7084	-99.90703	931392	2/16/2010 11:42		NATURAL GAS		1213	12427	0	NO						0	NO						0		YES		2/16/2010 12:50	2/16/2010 23:20					NO					NO							0	2/16/2010 8:18	2/16/2010 8:18	ONSHORE	OK	73660	REYDON	ROFER MILLS COUNTY	SURVEY STATION NO.	6428+12	CEGT AD-WEST		NO	PIPELINE RIGHT-OF-WAY	ABOVEGROUND	TYPICAL ABOVEGROUND FACILITY PIPING OR APPURTENANCE				NO																							INTERSTATE	ONSHORE PIPELINE, INCLUDING VALVE SITES	VALVE																																AUXILIARY OR OTHER VALVE							1974		CARBON STEEL		OTHER									1"X1/2" SWEDGE UNDER VALVE CRACKED	CLASS 1 LOCATION	NO		524		NO	NO	NO		0	0	65863	78601.6242984826	6429	3963.50970873786	3838	4580.3111619206	0	0	0	0			76130	42291.8537695774	87145.4451691411									904		1000	NOT ON OMB-APPROVED FORM WHEN SUBMITTED				PRESSURE DID NOT EXCEED MAOP	NO					AUTOMATIC	AUTOMATIC	79801	YES								NO							TRANSMISSION SYSTEM	YES	YES	YES	NO	NO	LOCAL OPERATING PERSONNEL, INCLUDING CONTRACTORS		OPERATOR EMPLOYEE	NO, THE OPERATOR DID NOT FIND THAT AN INVESTIGATION OF THE CONTROLLER(S) ACTIONS OR CONTROL ROOM ISSUES WAS NECESSARY DUE TO: (PROVIDE AN EXPLANATION FOR WHY THE OPERATOR DID NOT INVESTIGATE)	BECAUSE FIELD OPERATOR WAS INVOLVE WITH INCIDENT													YES	1	0	NO			EQUIPMENT FAILURE	THREADED CONNECTION/COUPLING FAILURE	MATERIAL/WELD/EQUIP FAILURE	THREADED CONNECTION/COUPLING FAILURE																																																																																																																																																																							THREADED CONNECTION/COUPLING FAILURE																OTHER	1"X1/2" SWEDGE TOP THREADS BROKE IN 1/2" VALVE																			YES	AGE OF SWEDGE CONNECTION																																																																																																																																																																		JOHNNY L. CAVITT	DOT COMPLIANCE MANAGER	johnny.cavitt@centerpointenergy.com	318-429-3606	318-429-3927				JOHNNY L. CAVITT	DOT COMPLIANCE MANAGER	318-429-3606	johnny.cavitt@centerpointenergy.com	AT APPROXIMATELY 08:18 HRS ON FEBRUARY 22, A FIELD EMPLOYEE WAS PERFORMING ANNUAL VALVE MAINTENANCE ON AUXILIARY VALVE ON CEGT LINE AD-WEST.  HE CONNECTED A CRESCENT WRENCH TO A 1'X 1/2 ' SWEDGE CONNECTION FOR THE 1/2 '  BALL VALVE AND IMMEDIATELY STARTED HEARING GAS LEAKING.  HE NOTIFIED SYSTEM CONTROL AT 08:25 HRS.  IT WAS FIRST THOUGHT THAT THE EVENT WOULD BE CORRECTED WITH MINOR COMPLICATIONS.  HOWEVER, AFTER EVALUATING THE SITUATION ALONG WITH FIELD EMPLOYEES, MANAGEMENT AND SYSTEM CONTROL IT WAS DECIDED THAT LINE AD-WEST WOULD HAVE TO BE BLOWN DOWN TO COMPLETE THE REPAIRS (APPROXIMATELY 10:18 HRS).  SYSTEM CONTROL CALCULATED THE LINE FILL AND IT WAS DETERMINED THAT THE BLOW DOWN WOULD BE @ 12,427 MCF VALUED AT $65,863.  SYSTEM CONTROL THEN NOTIFIED THE NRC AT 11:42.  THE LINE WAS BLOWN DOWN REPAIRS MADE AND THE LINE WAS BACK IN SERVICE BY 23:20 HRS.
		if (fgets (buffer, 16384, f)) {

			while (fgets (buffer, 16384, f)) {
				data = buffer;
				data.tokenize (",", &tokens, true, false);

				if (tokens.size () >= 635) {
					// one row is missing column [635] "narrative" 
					leak = gas_gathering->create_new (MAP_OBJECT_POINT);
					leak->id = atol (tokens [4].get_text_ascii ()); // REPORT_NUMBER
					leak->attributes_numeric [0]  = atol (tokens [8].get_text_ascii ()); // Operator_ID
					leak->attributes_text [0] = tokens[14]; // Local_DateTime

					if (tokens [18].get_length () > 0)
						leak->latitude = (long) (atof (tokens [18].get_text_ascii ()) * 1.0e6); // Location_Latitude 
					if (tokens [19].get_length () > 0)
						leak->longitude = (long) (atof (tokens [19].get_text_ascii ()) * 1.0e6); // Location_Longitude
					if (tokens [25].get_length () > 0)
						leak->attributes_numeric [1] = atof (tokens [25].get_text_ascii ()); // UNINTENTIONAL_RELEASE_BBLS
					gas_gathering->objects.push_back (leak);
				}
				else {
					log += "ERROR, unable to parse gas gathering data \"";
					log += buffer;
					log += "\"\n";
				}
			}
		}

		fclose (f);
		return true;
	}
	else {
		log += "ERROR, can't open Gas Gathering file \"";
		log += filename;
		log += "\".\n";
		return false;
	}
}

bool PipelineAccidents::read_hazardous_liquid
	(dynamic_string &filename,
	interface_window *view,
	dynamic_string &log)

{
	FILE *f;
	dynamic_string data;
	char buffer[16384];
	map_object *leak;
	std::vector <dynamic_string> tokens;

	view->update_progress (filename, 1);

	if (fopen_s (&f, filename.get_text_ascii (), "r") == 0) {
		// DATAFILE_AS_OF	SIGNIFICANT	SERIOUS	IPE	IA_IPE	OM_IPE	REPORT_NUMBER	SUPPLEMENTAL_NUMBER	REPORT_RECEIVED_DATE	REPORT_TYPE	OPERATOR_ID	NAME	OPERATOR_STREET_ADDRESS	OPERATOR_CITY_NAME	OPERATOR_STATE_ABBREVIATION	OPERATOR_POSTAL_CODE	LOCAL_DATETIME	IYEAR	LOCATION_LATITUDE	LOCATION_LONGITUDE	NRC_RPT_NUM	NRC_RPT_DATETIME	COMMODITY_RELEASED_TYPE	COMMODITY_SUBTYPE	COMMODITY_DETAILS	BLEND_DETAILS	BIO_DIESEL_DETAILS	UNINTENTIONAL_RELEASE_BBLS	INTENTIONAL_RELEASE_BBLS	RECOVERED_BBLS	NET_LOSS_BBLS	FATALITY_IND	NUM_EMP_FATALITIES	NUM_CONTR_FATALITIES	NUM_ER_FATALITIES	NUM_WORKER_FATALITIES	NUM_GP_FATALITIES	FATAL	INJURY_IND	NUM_EMP_INJURIES	NUM_CONTR_INJURIES	NUM_ER_INJURIES	NUM_WORKER_INJURIES	NUM_GP_INJURIES	INJURE	SHUTDOWN_DUE_ACCIDENT_IND	SHUTDOWN_EXPLAIN	SHUTDOWN_DATETIME	RESTART_DATETIME	STILL_SHUTDOWN_IND	IGNITE_IND	EXPLODE_IND	NUM_PUB_EVACUATED	INCIDENT_IDENTIFIED_DATETIME	ON_SITE_DATETIME	ON_OFF_SHORE	ONSHORE_STATE_ABBREVIATION	ONSHORE_POSTAL_CODE	ONSHORE_CITY_NAME	ONSHORE_COUNTY_NAME	DESIGNATED_LOCATION	DESIGNATED_NAME	PIPE_FAC_NAME	SEGMENT_NAME	FEDERAL	LOCATION_TYPE	INCIDENT_AREA_TYPE	INCIDENT_AREA_SUBTYPE	INCIDENT_AREA_DETAILS	DEPTH_OF_COVER	CROSSING	BRIDGE_CROSSING_IND	BRIDGE_TYPE	RAILROAD_CROSSING_IND	RAILROAD_TYPE	ROAD_CROSSING_IND	ROAD_TYPE	WATER_CROSSING_IND	WATER_TYPE	WATER_NAME	WATER_DEPTH	WATER_SUBTYPE	OFF_WATER_DEPTH	OFF_ACCIDENT_ORIGIN	OFFSHORE_STATE_ABBREVIATION	OFF_INSTATE_AREA	OFF_INSTATE_BLOCK	OFFSHORE_COUNTY_NAME	OFF_OCS_AREA	OFF_OCS_BLOCK	OFF_AREA_ACCIDENT_TYPE	PIPE_FACILITY_TYPE	SYSTEM_PART_INVOLVED	SYSTEM_SUBPART_INVOLVED	ITEM_INVOLVED	PIPE_TYPE	PIPE_DIAMETER	PIPE_WALL_THICKNESS	PIPE_SMYS	PIPE_SPECIFICATION	PIPE_SEAM_TYPE	PIPE_SEAM_DETAILS	PIPE_MANUFACTURER	PIPE_MANUFACTURE_YEAR	PIPE_COATING_TYPE	PIPE_COATING_DETAILS	WELD_SUBTYPE	WELD_DETAILS	VALVE_TYPE	VALVE_MAINLINE_TYPE	VALVE_MAINLINE_DETAILS	VALVE_MANUFACTURER	VALVE_MANUFACTURE_YEAR	TANK_VESSEL_SUBTYPE	ITEM_INVOLVED_DETAILS	TANK_VESSEL_DETAILS	INSTALLATION_YEAR	MATERIAL_INVOLVED	MATERIAL_DETAILS	RELEASE_TYPE	PUNCTURE_AXIAL	PUNCTURE_CIRCUM	LEAK_TYPE	LEAK_TYPE_OTHER	RUPTURE_ORIENT	RUPTURE_DETAILS	RUPTURE_WIDTH	RUPTURE_LENGTH	RELEASE_TYPE_DETAILS	WILDLIFE_IMPACT_IND	FISH_AQUATIC_IMPACT_IND	BIRDS_IMPACT_IND	TERRESTRIAL_IMPACT_IND	SOIL_CONTAMINATION	LONG_TERM_ASSESSMENT	REMEDIATION_IND	SURFACE_WATER_REMED_IND	GROUNDWATER_REMED_IND	SOIL_REMED_IND	VEGETATION_REMED_IND	WILDLIFE_REMED_IND	WATER_CONTAM_IND	OCEAN_SEAWATER_IND	SURFACE_CONTAM_IND	GROUNDWATER_CONTAM_IND	DRINKING_WATER_CONTAM_IND	PRIVATE_WELL_CONTAM_IND	PUBLIC_WATER_CONTAM_IND	AMOUNT_RELEASED	REL_WATER_NAME	COULD_BE_HCA	COMMODITY_REACHED_HCA	COMMERCIALLY_NAV_IND	COMMERCIALLY_NAV_YES_NO	HIGH_POP_IND	HIGH_POP_YES_NO	OTHER_POP_IND	OTHER_POP_YES_NO	USA_DRINKING_IND	USA_DRINKING_YES_NO	USA_ECOLOGICAL_IND	USA_ECOLOGICAL_YES_NO	EST_COST_OPER_PAID	EST_COST_OPER_PAID_CURRENT	EST_COST_GAS_RELEASED	EST_COST_GAS_RELEASED_CURRENT	EST_COST_PROP_DAMAGE	EST_COST_PROP_DAMAGE_CURRENT	EST_COST_EMERGENCY	EST_COST_EMERGENCY_CURRENT	EST_COST_ENVIRONMENTAL	EST_COST_ENVIRONMENTAL_CURRENT	EST_COST_OTHER	EST_COST_OTHER_CURRENT	EST_COST_OTHER_DETAILS	TOTAL_COST	TOTAL_COST_IN84	TOTAL_COST_CURRENT	ACCIDENT_PSIG	MOP_PSIG	ACCIDENT_PRESSURE	PRESSURE_RESTRICTION_IND	EXCEED_RESTRICTION_IND	PHMSA_RESTRICTION_IND	PART_C_QUESTION_2_IND	UPSTREAM_VALVE_TYPE_IND	DOWNSTREAM_VALVE_TYPE_IND	LENGTH_SEGMENT_ISOLATED	INTERNAL_INSPECTION_IND	DIAMETER_CHANGE_IND	UNSUITABLE_MAINLINE_IND	TIGHT_MITERED_IND	OTHER_RESTRICTIONS_IND	EXTRA_THICK_WALL_IND	OTHER_INSPECTION_IND	INTERNAL_INSPECTION_DETAILS	OPERATION_COMPLICATIONS_IND	EXCESSIVE_DEBRIS_IND	LOW_OP_PRESSURE_IND	LOW_FLOW_IND	INCOMPAT_COMMOD_IND	OTHER_COMPLICATIONS_IND	INSPECT_COMP_DETAILS	PIPELINE_FUNCTION	SCADA_IN_PLACE_IND	SCADA_OPERATING_IND	SCADA_FUNCTIONAL_IND	SCADA_DETECTION_IND	SCADA_CONF_IND	CPM_IN_PLACE_IND	CPM_OPERATING_IND	CPM_FUNCTIONAL_IND	CPM_DETECTION_IND	CPM_CONF_IND	ACCIDENT_IDENTIFIER	ACCIDENT_DETAILS	OPERATOR_TYPE	INVESTIGATION_STATUS	INVESTIGATION_STATUS_DETAILS	INVEST_SCHEDULE_IND	INVEST_NO_SCHEDULE_IND	INVEST_NO_SCHEDULE_IND_DETAILS	INVEST_NO_CONTROL_ROOM_IND	INVEST_NO_CONTROLLER_IND	INVEST_INCORRECT_ACTION_IND	INVEST_FATIGUE_IND	INVEST_INCORRECT_PROCEDURE_IND	INVEST_INCORRECT_CONTROL_IND	INVEST_MAINT_IND	INVEST_OTHER_IND	INVEST_OTHER_IND_DETAILS	EMPLOYEE_DRUG_TEST_IND	NUM_EMPLOYEES_TESTED	NUM_EMPLOYEES_FAILED	CONTRACTOR_DRUG_TEST_IND	NUM_CONTRACTORS_TESTED	NUM_CONTRACTORS_FAILED	CAUSE	CAUSE_DETAILS	MAP_CAUSE	MAP_SUBCAUSE	INTERNAL_EXTERNAL	VISUAL_EXAM_RESULTS	VISUAL_EXAM_DETAILS	GALVANIC_CORROSION_IND	ATMOSPHERE_CORROSION_IND	STRAY_CURRENT_CORROSION_IND	MICROBIOLOGICAL_CORROSION_IND	SELECTIVE_SEAM_CORROSION_IND	OTHER_CORROSION_IND	CORROSION_TYPE_DETAILS	FIELD_EXAM_BASIS_IND	METALLURGICAL_BASIS_IND	OTHER_BASIS_IND	CORROSION_BASIS_DETAILS	UNDERGROUND_LOCATION	UNDER_CATHODIC_PROTECTION_IND	CATHODIC_PRO_START_YEAR	SHIELDING_EVIDENT	CATHODIC_SURVEY_TYPE	CP_ANNUAL_SURVEY_IND	CLOSE_INTERVAL_SURVEY_IND	OTHER_CP_SURVEY_IND	CP_ANNUAL_SURVEY_YEAR	CLOSE_INTERVAL_SURVEY_YEAR	OTHER_CP_SURVEY_YEAR	EXTERNALLY_COATED	PRIOR_DAMAGE	INT_VISUAL_EXAM_RESULTS	INT_VISUAL_EXAM_DETAILS	INT_CORROSIVE_COMMODITY_IND	INT_WATER_ACID_IND	INT_MICROBIOLOGICAL_IND	INT_EROSION_IND	INT_OTHER_CORROSION_IND	INT_CORROSION_TYPE_DETAILS	INT_FIELD_EXAM_BASIS_IND	INT_METALLURGICAL_BASIS_IND	INT_OTHER_BASIS_IND	INT_CORROSION_BASIS_DETAILS	INT_LOW_POINT_PIPE_LOC_IND	INT_ELBOW_LOC_IND	INT_OTHER_LOC_IND	CORROSION_LOCATION_DETAILS	CORROSION_INHIBITORS	CORROSION_LINING	CLEANING_DEWATERING	CORROSION_COUPONS	API_STD_OUT_OF_SERVICE_IND	API_STD_OUT_OF_SERVICE_YEAR	API_STD_IN_SERVICE_IND	API_STD_IN_SERVICE_YEAR	COR_INSP_TOOL_COLL_IND	COR_MAGNETIC_FLUX_LEAKAGE_IND	COR_MAG_FLUX_LEAKAGE_YEAR	COR_ULTRASONIC_IND	COR_ULTRASONIC_YEAR	COR_GEOMETRY_IND	COR_GEOMETRY_YEAR	COR_CALIPER_IND	COR_CALIPER_YEAR	COR_CRACK_IND	COR_CRACK_YEAR	COR_HARDSPOT_IND	COR_HARDSPOT_YEAR	COR_COMBINATION_TOOL_IND	COR_COMBINATION_TOOL_YEAR	COR_TRANSVERSE_FIELD_IND	COR_TRANSVERSE_FIELD_YEAR	COR_INSPECTION_OTHER_IND	COR_INSPECTION_OTHER_YEAR	COR_INSPECTION_OTHER_DETAILS	COR_HYDROTEST_CONDUCTED_IND	COR_HYDROTEST_CONDUCTED_YEAR	COR_HYDROTEST_PRESSURE	DIRECT_INSPECTION_TYPE	DIRECT_YES_DIG_YEAR	DIRECT_YES_NO_DIG_YEAR	COR_NON_DESTRUCTIVE_IND	COR_RADIOGRAPHY_IND	COR_RADIOGRAPHY_YEAR	COR_GUIDED_WAVE_IND	COR_GUIDED_WAVE_YEAR	COR_HANDHELD_ULTRA_IND	COR_HANDHELD_ULTRA_YEAR	COR_WET_MAGNETIC_IND	COR_WET_MAGNETIC_YEAR	COR_DRY_MAGNETIC_IND	COR_DRY_MAGNETIC_YEAR	COR_NON_DEST_OTHER_IND	COR_NON_DEST_OTHER_YEAR	COR_NON_DEST_DETAILS	NATURAL_FORCE_TYPE	EARTH_SUBTYPE	HEAVY_RAINS_SUBTYPE	LIGHTNING_SUBTYPE	TEMPERATURE_SUBTYPE	NF_OTHER_DETAILS	NF_EXTREME_WEATHER_IND	NF_HURRICANE_IND	NF_TROPICAL_STORM_IND	NF_TORNADO_IND	NF_OTHER_IND	NF_EXTREME_WEATHER_DETAILS	PARTY_TYPE	EX_INSPECT_TOOL_COLLECTED_IND	EX_MAGNETIC_FLUX_LEAKAGE_IND	EX_MAGNETIC_FLUX_LEAKAGE_YEAR	EX_ULTRASONIC_IND	EX_ULTRASONIC_YEAR	EX_GEOMETRY_IND	EX_GEOMETRY_YEAR	EX_CALIPER_IND	EX_CALIPER_YEAR	EX_CRACK_IND	EX_CRACK_YEAR	EX_HARDSPOT_IND	EX_HARDSPOT_YEAR	EX_COMBINATION_TOOL_IND	EX_COMBINATION_TOOL_YEAR	EX_TRANSVERSE_FIELD_IND	EX_TRANSVERSE_FIELD_YEAR	EX_INSPECTION_OTHER_IND	EX_INSPECTION_OTHER_YEAR	EX_INSPECTION_OTHER_DETAILS	EX_BEFORE_DAMAGE	EX_HYDROTEST_CONDUCTED_IND	EX_HYDROTEST_CONDUCTED_YEAR	EX_HYDROTEST_PRESSURE	EX_DIRECT_INSPECTION_TYPE	EX_DIRECT_YES_DIG_YEAR	EX_DIRECT_YES_NO_DIG_YEAR	EX_NON_DESTRUCTIVE_IND	EX_RADIOGRAPHY_IND	EX_RADIOGRAPHY_YEAR	EX_GUIDED_WAVE_IND	EX_GUIDED_WAVE_YEAR	EX_HANDHELD_ULTRA_IND	EX_HANDHELD_ULTRA_YEAR	EX_WET_MAGNETIC_IND	EX_WET_MAGNETIC_YEAR	EX_DRY_MAGNETIC_IND	EX_DRY_MAGNETIC_YEAR	EX_NON_DEST_OTHER_IND	EX_NON_DEST_OTHER_YEAR	EX_NON_DEST_OTHER_DETAILS	PRIOR_NOTIFICATION_IND	ONE_CALL_SYSTEM_IND	EXCAVATOR_IND	CONTRACTOR_IND	LANDOWNER_IND	NOTIFY_CGA_DIRT	PUBLIC_ROW_IND	PUBLIC_SUBTYPE	PRIVATE_ROW_IND	PRIVATE_SUBTYPE	PIPELINE_EASEMENT_ROW_IND	POWER_TRANSMISSION_ROW_IND	RAILROAD_ROW_IND	PUBLIC_UTIL_EASEMENT_ROW_IND	FEDERAL_LAND_ROW_IND	DATA_NOT_COLLECTED_ROW_IND	UNKNOWN_ROW_IND	EXCAVATOR_TYPE	EXCAVATOR_EQUIPMENT	WORK_PERFORMED	ONE_CALL_NOTIFIED_IND	ONE_CALL_TICKET_NUM	ONE_CALL_CENTER_NAME	LOCATOR_TYPE	VISIBLE_MARKS	FACILITIES_MARKED	SERVICE_INTERRUPTION	SERVICE_INTERRUPTION_HOURS	ROOT_CAUSE	ONE_CALL_SUBTYPE	LOCATING_SUBTYPE	EXCAVATION_SUBTYPE	ROOT_CAUSE_OTHER	OUTSIDE_FORCE_TYPE	VEHICLE_SUBTYPE	OSF_HURRICANE_IND	OSF_TROPICAL_STORM_IND	OSF_TORNADO_IND	OSF_HEAVY_RAINS_IND	OSF_OTHER_WEATHER_IND	OSF_OTHER_WEATHER_DETAILS	OSF_INSPECT_TOOL_COLLECTED_IND	OSF_MAGNETIC_FLUX_LEAKAGE_IND	OSF_MAGNETIC_FLUX_LEAKAGE_YEAR	OSF_ULTRASONIC_IND	OSF_ULTRASONIC_YEAR	OSF_GEOMETRY_IND	OSF_GEOMETRY_YEAR	OSF_CALIPER_IND	OSF_CALIPER_YEAR	OSF_CRACK_IND	OSF_CRACK_YEAR	OSF_HARDSPOT_IND	OSF_HARDSPOT_YEAR	OSF_COMBINATION_TOOL_IND	OSF_COMBINATION_TOOL_YEAR	OSF_TRANSVERSE_FIELD_IND	OSF_TRANSVERSE_FIELD_YEAR	OSF_INSPECTION_OTHER_IND	OSF_INSPECTION_OTHER_YEAR	OSF_INSPECTION_OTHER_DETAILS	OSF_BEFORE_DAMAGE	OSF_HYDROTEST_CONDUCTED_IND	OSF_HYDROTEST_CONDUCTED_YEAR	OSF_HYDROTEST_PRESSURE	OSF_DIRECT_INSPECTION_TYPE	OSF_DIRECT_YES_DIG_YEAR	OSF_DIRECT_YES_NO_DIG_YEAR	OSF_NON_DESTRUCTIVE_IND	OSF_RADIOGRAPHY_IND	OSF_RADIOGRAPHY_YEAR	OSF_GUIDED_WAVE_IND	OSF_GUIDED_WAVE_YEAR	OSF_HANDHELD_ULTRA_IND	OSF_HANDHELD_ULTRA_YEAR	OSF_WET_MAGNETIC_IND	OSF_WET_MAGNETIC_YEAR	OSF_DRY_MAGNETIC_IND	OSF_DRY_MAGNETIC_YEAR	OSF_NON_DEST_OTHER_IND	OSF_NON_DEST_OTHER_YEAR	OSF_NON_DEST_DETAILS	INTENTIONAL_SUBTYPE	INTENTIONAL_DETAILS	OSF_OTHER_DETAILS	FIELD_EXAM_IND	METALLURGICAL_IND	OTHER_ANALYSIS_IND	OTHER_ANALYSIS_DETAILS	STILL_UNDER_INVEST_IND	FAILURE_TYPE	FATIGUE_VIBR_RELATED_1	FAILURE_SUBTYPE_1	FATIGUE_VIBR_RELATED_OTHER_1	MECHANICAL_STRESS_1	OTHER_FACTOR_1	OTHER_FACTOR_DETAILS_1	FATIGUE_VIBR_RELATED_2	FAILURE_SUBTYPE_2	FATIGUE_VIBR_RELATED_OTHER_2	MECHANICAL_STRESS_2	OTHER_FACTOR_2	OTHER_FACTOR_DETAILS_2	STRESS_SUBTYPE	STRESS_DETAILS	ADDITIONAL_DENT_IND	ADDITIONAL_GOUGE_IND	ADDITIONAL_PIPE_BEND_IND	ADDITIONAL_ARC_BURN_IND	ADDITIONAL_CRACK_IND	ADDITIONAL_LACK_FUSION_IND	ADDITIONAL_LAMINATION_IND	ADDITIONAL_BUCKLE_IND	ADDITIONAL_WRINKLE_IND	PWF_ADDL_MISALIGNMENT_IND	ADDITIONAL_BURNT_STEEL_IND	PWF_ADDITIONAL_OTHER_IND	PWF_ADDITIONAL_OTHER_DETAILS	PWF_INSP_TOOL_COLLECTED_IND	PWF_MAGNETIC_FLUX_LEAKAGE_IND	PWF_MAG_FLUX_LEAKAGE_YEAR	PWF_ULTRASONIC_IND	PWF_ULTRASONIC_YEAR	PWF_GEOMETRY_IND	PWF_GEOMETRY_YEAR	PWF_CALIPER_IND	PWF_CALIPER_YEAR	PWF_CRACK_IND	PWF_CRACK_YEAR	PWF_HARDSPOT_IND	PWF_HARDSPOT_YEAR	PWF_COMBINATION_TOOL_IND	PWF_COMBINATION_TOOL_YEAR	PWF_TRANSVERSE_FIELD_IND	PWF_TRANSVERSE_FIELD_YEAR	PWF_INSPECTION_OTHER_IND	PWF_INSPECTION_OTHER_YEAR	PWF_INSPECTION_OTHER_DETAILS	PWF_HYDROTEST_CONDUCTED_IND	PWF_HYDROTEST_CONDUCTED_YEAR	PWF_HYDROTEST_PRESSURE	PWF_DIRECT_INSPECTION_TYPE	PWF_DIRECT_YES_DIG_YEAR	PWF_DIRECT_YES_NO_DIG_YEAR	PWF_NON_DEST_IND	PWF_RADIOGRAPHY_IND	PWF_RADIOGRAPHY_YEAR	PWF_GUIDED_WAVE_IND	PWF_GUIDED_WAVE_YEAR	PWF_HANDHELD_ULTRA_IND	PWF_HANDHELD_ULTRA_YEAR	PWF_WET_MAGNETIC_IND	PWF_WET_MAGNETIC_YEAR	PWF_DRY_MAGNETIC_IND	PWF_DRY_MAGNETIC_YEAR	PWF_NON_DEST_OTHER_IND	PWF_NON_DEST_OTHER_YEAR	PWF_NON_DEST_OTHER_DETAILS	EQ_FAILURE_TYPE	CONTROL_VALVE_IND	INSTRUMENTATION_IND	SCADA_IND	COMMUNICATIONS_IND	BLOCK_VALVE_IND	CHECK_VALVE_IND	RELIEF_VALVE_IND	POWER_FAILURE_IND	STOPPLE_CONTROL_FITTING_IND	ESD_SYSTEM_FAILURE_IND	OTHER_CONTROL_RELIEF_IND	OTHER_CONTROL_RELIEF_DETAILS	OTHER_PUMP_IND	OTHER_PUMP_DETAILS	OTHER_STRIPPED_IND	OTHER_STRIPPED_DETAILS	OTHER_NON_THREADED_IND	OTHER_NON_THREADED_DETAILS	FAILURE_DETAILS	ADDITIONAL_VIBRATION_IND	ADDITIONAL_OVERPRESSURE_IND	ADDITIONAL_SUPPORT_IND	ADDITIONAL_DEFECT_IND	ADDITIONAL_ELECTRICITY_IND	ADDITIONAL_INSTALLATION_IND	ADDITIONAL_MISMATCH_IND	ADDITIONAL_DISSIMILAR_IND	ADDITIONAL_BREAKDOWN_IND	ADDITIONAL_VALVE_IND	ADDITIONAL_ALARM_IND	IEF_ADDL_MISALIGNMENT_IND	ADDITIONAL_THERMAL_IND	EQ_ADDITIONAL_OTHER_IND	EQ_ADDITIONAL_OTHER_DETAILS	OPERATION_TYPE	OVERFLOW_OTHER_IND	OVERFLOW_OTHER_DETAILS	OPERATION_DETAILS	RELATED_INADEQUATE_PROC_IND	RELATED_NO_PROC_IND	RELATED_FAILURE_FOLLOW_IND	RELATED_OTHER_IND	OPERATION_RELATED_DETAILS	CATEGORY_TYPE	OPERATOR_QUALIFICATION_IND	QUALIFIED_INDIVIDUALS	OTHER_TYPE	MISC_DETAILS	UNKNOWN_SUBTYPE	SPILL_TYPE_CATEGORY	PREPARER_NAME	PREPARER_TITLE	PREPARER_EMAIL	PREPARER_TELEPHONE	PREPARER_FAX	PREPARED_DATE	AUTHORIZER_NAME	AUTHORIZER_TITLE	AUTHORIZER_TELEPHONE	AUTHORIZER_EMAIL	NARRATIVE
		// 2/26/2021	NO	NO	NO	NO	NO	20100001	15751	3/10/2010	SUPPLEMENTAL FINAL	22610	MAGELLAN PIPELINE COMPANY, LP	MAGELLAN MIDSTREAM PARTNERS, L.P.	TULSA	OK	74172	2/16/2010 7:42	2010	41.94352	-88.23353			REFINED AND/OR PETROLEUM PRODUCT (NON-HVL) WHICH IS A LIQUID AT AMBIENT CONDITIONS	DIESEL, FUEL OIL, KEROSENE, JET FUEL				0.12	0	0.12	0	NO							NO							NO	LINE WAS INACTIVE AT THE TIME.				NO	NO		2/16/2010 7:42	2/16/2010 7:45	ONSHORE	IL	60184	WAYNE	DUPAGE	MILEPOST/VALVE STATION	286	WAYNE JUNCTION	WAYNE JUNCTION BYPASS LINE	NO	TOTALLY CONTAINED ON OPERATOR-CONTROLLED PROPERTY	ABOVEGROUND	TYPICAL ABOVEGROUND FACILITY PIPING OR APPURTENANCE			NO																					INTERSTATE	ONSHORE PIPELINE, INCLUDING VALVE SITES		VALVE														MAINLINE	PLUG		GENERAL TWIN SEAL	2000				2000	MATERIAL OTHER THAN CARBON STEEL	GASKET IN BOTTOM PLATE ON VALVE	LEAK			SEAL OR PACKING							NO				YES	NO	YES			YES			NO									YES	YES									YES	YES	0	0	15	17.9011639991686	25900	30909.3431718977	1500	1790.11639991686	1900	2267.48077322802	1200	1432.09311993349	ROCK FOR DRIVEWAY INTO VALVE SITE.	30515	16716.3339222615	36416.9346289753	385	1440	PRESSURE DID NOT EXCEED MOP	NO			YES	MANUAL	REMOTELY CONTROLLED	26400	NO	YES	YES	YES			YES	THIS VALVE IS LOCATED ON A BYPASS LINE	NO							> 20% SMYS REGULATED TRUNKLINE/TRANSMISSION	YES	YES	YES	NO	NO	NO					LOCAL OPERATING PERSONNEL, INCLUDING CONTRACTORS		OPERATOR EMPLOYEE	NO, THE OPERATOR DID NOT FIND THAT AN INVESTIGATION OF THE CONTROLLER(S) ACTIONS OR CONTROL ROOM ISSUES WAS NECESSARY	RELEASE WAS FROM A FAULTY GASKET													NO			NO			EQUIPMENT FAILURE	NON-THREADED CONNECTION FAILURE	MATERIAL/WELD/EQUIP FAILURE	NON-THREADED CONNECTION FAILURE																																																																																																																																																																																																																																																																																																																NON-THREADED CONNECTION FAILURE																	GASKET																YES	ICE IN THE BOTTOM OF THE VALVE MAY HAVE CONTRIBUTED GASKET FAILURE																SMALL	KENNETH L. LYBARGER	SENIOR COMPLIANCE COORDINATOR	ken.lybarger@magellanlp.com	918-574-7315	918-574-7246	4/15/2011	KENNETH L. LYBARGER	SENIOR COMPLIANCE COORDINATOR	918-574-7315	ken.lybarger@magellanlp.com	
		// 2/26/2021	NO	NO	NO	NO	NO	20100002	19837	3/16/2010	SUPPLEMENTAL FINAL	31672	CHAPARRAL ENERGY, LLC	701 CEDAR LAKE BLVD 	OKLAHOMA CITY	OK	73114	3/1/2010 11:50	2010	37.10847	-100.80037			CO2 (CARBON DIOXIDE)					2.99		0	2.99	NO							NO							YES		3/1/2010 11:51	3/5/2010 2:00		NO	NO	0	3/1/2010 11:50	3/1/2010 11:50	ONSHORE	KS	67901	HAYNE	SEWARD					NO	PIPELINE RIGHT-OF-WAY	ABOVEGROUND	TYPICAL ABOVEGROUND FACILITY PIPING OR APPURTENANCE			NO																					INTERSTATE	ONSHORE PIPELINE, INCLUDING VALVE SITES		OTHER																				RELIEF VALVE AND SUPPORT			CARBON STEEL		OTHER									Improper Design of Relief Valve Support	NO				NO	NO	NO						NO									NO	NO											0	0	10	11.934109332779	3500	4176.93826647267	0	0	0	0	0	0		3510	1922.80295156932	4188.87237580545	1613	1620	PRESSURE DID NOT EXCEED MOP	NO			YES	MANUAL	MANUAL	4	YES								NO							> 20% SMYS REGULATED TRUNKLINE/TRANSMISSION	YES	YES	YES	NO	YES	NO					LOCAL OPERATING PERSONNEL, INCLUDING CONTRACTORS		OPERATOR EMPLOYEE	YES		YES			YES	YES						YES	Improper design of relief valve support	YES	1	0	NO			OTHER INCIDENT CAUSE	MISCELLANEOUS	ALL OTHER CAUSES	MISCELLANEOUS																																																																																																																																																																																																																																																																																																																																																															MISCELLANEOUS	IMPROPER DESIGN OF RELIEF VALVE SUPPORT		SMALL	GABE MCCOWN	SR. PIPELINE TECH II	gabe.mccown@chaparralenergy.com	405-426-4361		10/28/2014	DAVE YEAGER	PIPELINE MANAGER	405-255-6581	dave.yeager@chaparralenergy.com	AT 11:50 AM ON THE MORNING OF MARCH 1, 2010 A CHAPARRAL ENERGY, LLC OPERATOR WORKING ON THE GROUNDS OF THE CHAPARRAL ENERGY ARKALON CO2 PLANT LOCATED IN HAYNE, KS HEARD VENTING CO2.  THE EMPLOYEE PROCEEDED IMMEDIATELY TO INVESTIGATE THE CAUSE OF THE RELEASE AND FOUND THAT THE RELIEF VALVE ON THE CHAPARRAL ENERGY OPERATED HAYNE-BOOKER CO2 PIPELINE HAD RELIEVED AND THAT THE PIPE BELOW THE VALVE HAD FAILED CAUSING DAMAGE TO THE RELIEF SYSTEM.  AT 11:51AM THE OPERATOR BEGAN SHUTTING DOWN THE CO2 PIPELINE, THE LINE WAS SHUT DOWN BY 11:55AM.      INTERNAL INVESTIGATION OF THE ACCIDENT DETERMINED THAT THE FAILURE AND SUBSEQUENT LEAK OCCURRED DUE TO A DESIGN FLAW IN THE SUPPORT FOR THE RELIEF VALVE.  THERE WAS NO OPERATOR/CONTROLLER ISSUES INVOLVED IN THE CAUSE OF THE INCIDENT.      THE RELIEF VALVE SUPPORT HAS BEEN REDESIGNED TO ELIMINATE THE POSSIBILITY OF FUTURE REOCCURRENCES.  THIS PROCESS HAS BEEN REPEATED ON ALL RELIEF VALVES ASSOCIATED WITH THIS LINE.  THE NEW DESIGN HAS BEEN INCORPORATED INTO THE COMPANY DESIGN STANDARD TO PREVENT SIMILAR OCCURRENCES ON FUTURE LINES.      REPAIRS WERE COMPLETED ON MARCH 5, 2010.  STARTUP OF THE LINE COMPLETED AT 2:00PM ON MARCH 5.    THIS IS TO CLOSE OUT THIS REPORT, NOTHING NEW TO REPORT.
		// 2/26/2021	YES	NO	NO	NO	NO	20100003	18021	3/17/2010	SUPPLEMENTAL FINAL	32035	LDH ENERGY PIPELINE L.P.	13430 NORTHWEST FREEWAY   SUITE 1200 	HOUSTON	TX	77040-6019	2/22/2010 10:38	2010	32.22471	-101.4044			HVL OR OTHER FLAMMABLE OR TOXIC FLUID WHICH IS A GAS AT AMBIENT CONDITIONS	LPG (LIQUEFIED PETROLEUM GAS)  /  NGL (NATURAL GAS LIQUID)				1	116	0	1	NO							NO							NO	ABLE TO BYPASS LEAK AREA.				NO	NO	0			ONSHORE	TX	79720-0000	BIG SPRING	HOWARD	MILEPOST/VALVE STATION	MP 40	W. TX. NGL	12" LOOP LINE	NO	PIPELINE RIGHT-OF-WAY	UNDERGROUND	UNDER SOIL		24	NO																					INTRASTATE	ONSHORE PIPELINE, INCLUDING VALVE SITES		WELD, INCLUDING HEAT-AFFECTED ZONE		12.75	0.235	42000	5LX-42	LONGITUDINAL ERW - LOW FREQUENCY		UNKNOWN	1953	COAL TAR		PIPE GIRTH WELD										1955	CARBON STEEL		LEAK			PINHOLE							NO				NO	NO	NO						NO									NO	NO											0	0	2360	2816.44980253586	0	0	0	0	0	0	24500	29238.5678653087	RESPONSE, REPAIRS, CONTRACT LABOR	26860	14714.0989399293	32055.0176678445	600	800	PRESSURE DID NOT EXCEED MOP	NO			YES	MANUAL	MANUAL	42240	YES								NO							> 20% SMYS REGULATED TRUNKLINE/TRANSMISSION	YES	YES	YES	NO	NO	NO					LOCAL OPERATING PERSONNEL, INCLUDING CONTRACTORS		CONTRACTOR WORKING FOR THE OPERATOR	NO, THE OPERATOR DID NOT FIND THAT AN INVESTIGATION OF THE CONTROLLER(S) ACTIONS OR CONTROL ROOM ISSUES WAS NECESSARY	PIHOLE LEAK, COULD NOT HAV BEEN DETECTED BY CONTROLLER													NO			NO			CORROSION FAILURE	EXTERNAL CORROSION	CORROSION	EXTERNAL	EXTERNAL CORROSION	LOCALIZED PITTING							YES	DISBONDED COATING	YES				YES	YES	1955	YES	YES	YES			2009				YES																									YES							YES	2008												YES	2008	1440	YES, BUT THE POINT OF THE ACCIDENT WAS NOT IDENTIFIED AS A DIG SITE		2008	NO																																																																																																																																																																																																																																																																																				SMALL	DANNY NICHOLS	DIRECTOR - REGULATORY COMPLIANCE	danny.nichols@energytransfer.com	326-681-006 		5/10/2013	DANNY NICHOLS	DIRECTOR - REGULATORY COMPLIANCE	326-681-006 	danny.nichols@energytransfer.com	LEAK DISCOVERED BY CONTRACTOR WORKING FOR ANOTHER COMPANY, PIPELINE OPERATOR DISPATCHED TO LOCATION, LEAK CONFIRMED, PIPELINE ISOLATED, AREA MADE SAFE AND RESPONSE/REPAIR CREWS DISPATCED TO LOCATION, PIPELINE STOPPLED OFF, PERMANENT REPAIRS MADE BY REPLACING DAMAGED SECTION WITH NEW TESTED PIPE.  ALL AGENCY NOTIFICATIONS MADE IN ACCORDANCE WITH REGULATORY REGULATIONS AND COMPANY PROCEDURES.  REPAIRS COMPLETED, PIPELINE RESUMED NORMAL OPERATIONS.
		if (fgets (buffer, 16384, f)) {

			while (fgets (buffer, 16384, f)) {
				data = buffer;
				data.tokenize (",", &tokens, true, false);

				if (tokens.size () == 606) {
					leak = hazardous_liquid->create_new (MAP_OBJECT_POINT);
					leak->id = atol (tokens [6].get_text_ascii ()); // REPORT_NUMBER
					leak->attributes_numeric [0]  = atol (tokens [10].get_text_ascii ()); // Operator_ID
					leak->attributes_text [0] = tokens[16]; // Local_DateTime

					if (tokens [18].get_length () > 0)
						leak->latitude = (long) (atof (tokens [18].get_text_ascii ()) * 1.0e6); // Location_Latitude 
					if (tokens [19].get_length () > 0)
						leak->longitude = (long) (atof (tokens [19].get_text_ascii ()) * 1.0e6); // Location_Longitude
					if (tokens [27].get_length () > 0)
						leak->attributes_numeric [1] = atof (tokens [27].get_text_ascii ()); // UNINTENTIONAL_RELEASE_BBLS

					hazardous_liquid->objects.push_back (leak);
				}
				else {
					log += "ERROR, unable to parse hazardous liquid data \"";
					log += buffer;
					log += "\"\n";
				}
			}
		}

		fclose (f);
		return true;
	}
	else {
		log += "ERROR, can't open Hazardous Liquid file \"";
		log += filename;
		log += "\".\n";
		return false;
	}
}


bool PipelineAccidents::read_liquified_natural_gas
	(dynamic_string &filename,
	interface_window *view,
	dynamic_string &log)

{
	FILE *f;
	dynamic_string data;
	char buffer[16384];
	map_object *leak;
	std::vector <dynamic_string> tokens;

	view->update_progress (filename, 1);

	if (fopen_s (&f, filename.get_text_ascii (), "r") == 0) {
		// DATAFILE_AS_OF	SIGNIFICANT	SERIOUS	REPORT_NUMBER	SUPPLEMENTAL_NUMBER	REPORT_RECEIVED_DATE	REPORT_TYPE	OPERATOR_ID	NAME	OPERATOR_STREET_ADDRESS	OPERATOR_CITY_NAME	OPERATOR_STATE_ABBREVIATION	OPERATOR_POSTAL_CODE	LOCAL_DATETIME	IYEAR	NRC_RPT_NUM	NRC_RPT_DATETIME	UNINTENTIONAL_RELEASE_IND	INTENTIONAL_RELEASE_IND	EMERGENCY_SHUTDOWN_IND	RESULTED_FROM_OTHER_IND	RESULTED_FROM_OTHER_DETAILS	COMMODITY_RELEASED_TYPE	COMMODITY_DETAILS	UNINTENTIONAL_RELEASE	INTENTIONAL_RELEASE	VOLUME_TO_GROUND	FATALITY_IND	NUM_EMP_FATALITIES	NUM_CONTR_FATALITIES	NUM_ER_FATALITIES	NUM_GP_FATALITIES	FATAL	INJURY_IND	NUM_EMP_INJURIES	NUM_CONTR_INJURIES	NUM_ER_INJURIES	NUM_GP_INJURIES	INJURE	SHUTDOWN_DUE_ACCIDENT_IND	SHUTDOWN_EXPLAIN	SHUTDOWN_DATETIME	RESTART_DATETIME	STILL_SHUTDOWN_IND	IGNITE_IND	EXPLODE_IND	NUM_PUB_EVACUATED	NUM_OPER_AND_CONTRACTOR_EVAC	FACILITY_NAME	NPMS_LNG_ID	FACILITY_STATUS	FACILITY_LATITUDE	FACILITY_LONGITUDE	FACILITY_STATE	FACILITY_LIQUID_VAPOR_RATE	FACILITY_NUM_VAPORIZERS	FACILITY_TOTAL_CAPACITY	FACILITY_SOURCE_TRUCK_IND	FACILITY_SOURCE_RAILROAD_IND	FACILITY_SOURCE_MARINE_IND	FACILITY_SOURCE_LIQUEFY_IND	INTER_INTRA	FACILITY_NUMBER_TANKS	FACILITY_VOLUME_STORAGE	FACILITY_TYPE_BASE_LOAD_IND	FACILITY_TYPE_PEAK_SHAVE_IND	FACILITY_TYPE_SATELLITE_IND	FACILITY_TYPE_MOBILE_TEMP_IND	SUB_MOBILE_TEMP_INTRASTATE_IND	SUB_MOBILE_TEMP_INTERSTATE_IND	FACILITY_TYPE_OTHER_IND	FACILITY_TYPE_OTHER_DETAILS	FUNCTION_MARINE_TERMINAL_IND	SUB_MARINE_IMPORT_TERMINAL_IND	SUB_MARINE_EXPORT_TERMINAL_IND	FUNCTION_STORAGE_IND	SUB_STORAGE_WITH_LIQUEFY_IND	SUB_STORAGE_WO_LIQUEFY_IND	FUNCTION_STRANDED_UTILITY_IND	FUNCTION_VEHICULAR_FUEL_IND	FUNCTION_NITRO_SPECIAL_USE_IND	FUNCTION_SPECIAL_USE_DETAILS	ITEM_INVOLVED	ITEM_INVOLVED_DETAILS	EST_COST_OPER_PAID	EST_COST_OPER_PAID_CURRENT	EST_COST_PROP_DAMAGE	EST_COST_PROP_DAMAGE_CURRENT	EST_COST_EMERGENCY	EST_COST_EMERGENCY_CURRENT	EST_COST_OTHER	EST_COST_OTHER_CURRENT	EST_COST_OTHER_DETAILS	EST_COST_GAS_RELEASED	EST_COST_GAS_RELEASED_CURRENT	EST_COST_INTENTIONAL_RELEASE	EST_COST_INTENT_REL_CURRENT	TOTAL_COST	TOTAL_COST_IN84	TOTAL_COST_CURRENT	CCS_IN_PLACE_IND	CCS_OPERATING_IND	CCS_FUNCTIONAL_IND	ACCIDENT_IDENTIFIER	ACCIDENT_DETAILS	EMPLOYEE_DRUG_TEST_IND	NUM_EMPLOYEES_TESTED	NUM_EMPLOYEES_FAILED	CONTRACTOR_DRUG_TEST_IND	NUM_CONTRACTORS_TESTED	NUM_CONTRACTORS_FAILED	CAUSE	CAUSE_DETAILS	MAP_CAUSE	MAP_SUBCAUSE	INTERNAL_EXTERNAL	NATURAL_FORCE_TYPE	NF_OTHER_DETAILS	PARTY_TYPE	OUTSIDE_FORCE_TYPE	OSF_VEHICLE_SUBTYPE	OSF_HURRICANE_IND	OSF_TROPICAL_STORM_IND	OSF_TORNADO_IND	OSF_HEAVY_RAINS_IND	OSF_OTHER_WEATHER_IND	OSF_OTHER_WEATHER_DETAILS	OSF_INTENTIONAL_SUBTYPE	OSF_INTENTIONAL_DETAILS	OSF_INTENT_SECURITY_BREACH_IND	OSF_OTHER_DETAILS	PWJF_FIELD_EXAM_IND	PWJF_METALLURGICAL_IND	PWJF_OTHER_ANALYSIS_IND	PWJF_STILL_UNDER_INVEST_IND	PWJF_FAILURE_TYPE	PWJF_INSULATION_DEGRAD_IND	EQ_FAILURE_TYPE	EQ_FAILURE_DETAILS	EQ_LOW_TEMP_EMBRITTLEMENT_IND	EQ_INSULATION_DEGRADATION_IND	OPERATION_TYPE	OPERATION_DETAILS	RELATED_INADEQUATE_PROC_IND	RELATED_NO_PROC_IND	RELATED_FAILURE_FOLLOW_IND	RELATED_OTHER_IND	OPERATION_RELATED_DETAILS	OTHER_TYPE	MISC_DETAILS	UNKNOWN_SUBTYPE	PREPARER_NAME	PREPARER_TITLE	PREPARER_EMAIL	PREPARER_TELEPHONE	PREPARER_FAX	PREPARED_DATE	AUTHORIZER_NAME	AUTHORIZER_TITLE	AUTHORIZER_TELEPHONE	AUTHORIZER_EMAIL	NARRATIVE
		// 2/26/2021	NO	NO	20120001	15002	11/28/2012	SUPPLEMENTAL FINAL	13840	NORTHWEST NATURAL GAS CO	250 SW TAYLOR ST 	PORTLAND	OR	97204	11/4/2012 14:38	2012	1029623	11/4/2012 16:00	NO	NO	YES	NO		OTHER COMMODITY	CO2	230			NO					0	NO					0	YES		11/4/2012 14:38	11/7/2012 11:00		NO	NO	0	0	NEWPORT LNG PLANT	NEWPORT	IN SERVICE	44.62425232	-124.0266953	OR	6	0	6				YES	INTRASTATE	1	165000		YES										YES	YES						OTHER	Plant Control System	0	0	10000	11483	0	0	0	0		0	0	0	0	10000	5271	11483	YES	YES	NO	OTHER	COMPUTERIZED CONTROL SYSTEM AND LOCAL OPERATING PERSONNEL.	NO			NO			EQUIPMENT FAILURE	OTHER EQUIPMENT FAILURE	MATERIAL/WELD/EQUIP FAILURE	OTHER EQUIPMENT FAILURE																							OTHER EQUIPMENT FAILURE	PLANT CONTROL SYSTEM	NO	NO											ANDREA SCOTT	COMPLIANCE SPECIALIST	a3s@nwnatural.com	503-226-4211		12/18/2012	KERRY SHAMPINE	MANAGER CODE COMPLIANCE	503-226-4211	kfs@nwnatural.com	ON SUNDAY NOVEMBER 4, 2012 AT APPROXIMATELY 2:30PM PST AN EVENT OCCURRED AT NW NATURAL¿S NEWPORT LNG STORAGE PLANT LOCATED AT 1702 YAQUINA BAY RD IN NEWPORT, OREGON.  THE PLANT WAS OPERATING IN LIQUEFACTION MODE AND EXPERIENCED AN UNPLANNED SHUTDOWN OF ITS LIQUEFACTION PROCESS.  ON-SITE PERSONNEL RESPONDED APPROPRIATELY AND RETURNED THE PLANT TO HOLD MODE AND VERIFIED SAFE CONDITIONS.  THERE WAS A SMALL CYCLING RELEASE OF CO2 FROM A VESSEL THROUGH ITS RELIEF VALVE FOR A PERIOD OF ABOUT 20 MINUTES.  FURTHER RESEARCH OVER THE NEXT 24 HOURS CONFIRMED THE PRIMARY CAUSE OF THE EVENT AS THE FAILURE OF AN ALLEN-BRADLEY PLC-5/40E PROCESSOR BOARD.  THIS PLC WAS PROGRAMMED AS THE CONTROL PLC FOR THE PLANT LIQUEFACTION PROCESS.  A REPLACEMENT PLC WAS PROCURED AND DELIVERED TO THE PLANT ON WEDNESDAY NOVEMBER 7, 2012.  THE LIQUEFACTION PLC PROGRAM WAS RELOADED INTO THE NEW PROCESSOR AND ITS FUNCTIONALITY WAS VERIFIED THAT SAME DAY.  THE PLANT WAS DECLARED BACK IN SERVICE BY NOON WEDNESDAY NOVEMBER 7, 2012.
		// 2/26/2021	NO	NO	20140001	15015	1/29/2014	SUPPLEMENTAL FINAL	13750	NORTHERN NATURAL GAS CO	1111 SOUTH 103RD STREET 	OMAHA	NE	68124	12/31/2013 7:00	2013	1069801	12/31/2013 9:37	YES	NO	NO	NO		NATURAL GAS WHILE BEING HANDLED IN GASEOUS PHASE		1	0	0	NO					0	NO					0	YES		12/31/2013 7:05		YES	YES	NO	0	0	Portable tanker and vaporizer		IN SERVICE			MN	1025	1	6000	YES				INTERSTATE	2	234				YES		YES									YES				RELIEF VALVE		0	0	1000	1127.55302435192	0	0	0	0		500	390.368852459016	0	0	1500	922.289705484656	1517.92187681094	NO			LOCAL OPERATING PERSONNEL, INCLUDING CONTRACTORS WORKING FOR THE OPERATOR		NO			NO			EQUIPMENT FAILURE	MALFUNCTION OF CONTROL/RELIEF EQUIPMENT	MATERIAL/WELD/EQUIP FAILURE	MALFUNCTION OF CONTROL/RELIEF EQUIPMENT																							MALFUNCTION OF CONTROL/RELIEF EQUIPMENT		NO	NO											JOHN GORMLEY	SR. CORROSION SPECIALIST	john.gormley@nngco.com	402-398-7494		4/25/2016	THOMAS CORRELL	DIRECTOR OF PIPELINE SAFETY	402-398-7715	thomas.correll@nngco.com	ON TUESDAY, DECEMBER 31, 2013 AT APPROXIMATELY 0700 CST A FLASH FIRE OCCURRED DURING LIQUIFIED NATURAL GAS DELIVERY OPERATIONS AT THE BENSON, MINNESOTA TOWN BORDER STATION. INFORMATION INDICATES THE CAUSE OF THE FLASH FIRE WAS A CATASTROPHIC FAILURE OF A FUEL RUN REGULATOR LOCATED ON THE VAPORIZER TRAILER. THE REGULATOR FAILURE CAUSED MULTIPLE RELIEF VALVES TO EXHAUST GAS TO THE ATMOSPHERE WHICH WAS IGNITED BY THE WATER/GLYCOL HEATER BURNERS LOCATED ON THE VAPORIZER TRAILER. TWO EMPLOYEES WERE EXAMINED AT A NEARBY HOSPITAL AND RELEASED BACK TO FULL DUTY. THEY BOTH HAD SUNBURN LIKE INJURIES.    NORTHERN HAD PLACED THIS TEMPORARY / PORTABLE LNG TANKER AND VAPORIZER TAILER AT THE BENSON, MINNESOTA TOWN BORDER STATION AS A CONTINGENCY WHILE WORK WAS BEING CONDUCTED UPSTREAM AT THE ALEXANDRIA, MINNESOTA COMPRESSOR STATION. THE TANKER AND VAPORIZER HAD BEEN CONNECTED TO THE BENSON TOWN BORDER STATION SINCE 12/27/2013 BUT WASN'T IN-SERVICE UNTIL THE MORNING OF 12/31/2013. THE WATER BATH HEATERS ON THE VAPORIZER TRAILER WERE LIT BUT LNG WAS NOT BEING DELIVERED. ON 12/31/2013, THE PIPELINE GAS PRESSURE WAS LOW ENOUGH TO TEST THE LNG DELIVERY. THE DELIVERY WAS JUST BEGINNING TO COME ON WHEN THE REGULATOR FAILED AND THE FLASH FIRE OCCURRED. THE TOWN OF BENSON, MINNESOTA WAS NEVER IN DANGER OF LOSING NATURAL GAS SERVICE.
		// 2/26/2021	YES	YES	20140002	15014	5/6/2014	SUPPLEMENTAL FINAL	39054	WILLIAMS PARTNERS OPERATING LLC	ONE WILLIAMS CENTER 	TULSA	OK	74172	3/31/2014 8:19	2014	1078325	3/31/2014 9:23	YES	NO	NO	NO		NATURAL GAS WHILE BEING HANDLED IN GASEOUS PHASE		14000	154200	0	NO					0	YES	1	0	0	0	1	YES		3/31/2014 8:19	3/15/2016 8:15		YES	YES	150	18	Plymouth LNG Peak Shaving Plant		IN SERVICE			WA	0	0	300				YES	INTERSTATE	2	344309		YES										YES	YES						IN-PLANT PIPING		71300	78868.8854638281	40790000	45120081.8803584	190000	210169.540506695	4698000	5196718.42789712	Purification system upgrade, certain MI inspections and enviro monitoring.	80960	54020.5954465849	672800	448926.094570928	46503060	23750842.9775636	51108785.4242435	YES	YES	YES	LOCAL OPERATING PERSONNEL, INCLUDING CONTRACTORS WORKING FOR THE OPERATOR		YES	16	0	NO			INCORRECT OPERATION	OTHER INCORRECT OPERATION 	INCORRECT OPERATION	OTHER INCORRECT OPERATION																											OTHER INCORRECT OPERATION 	INADEQUATE PURGE FOLLOWING MAINTENANCE ACTIVITIES.	YES								JARED ELLSWORTH	MANAGER PIPELINE SAFETY	jared.ellsworth@williams.com	8015846539		3/25/2016	JARED ELLSWORTH	MANAGER PIPELINE SAFETY	8015846539	jared.ellsworth@williams.com	AT APPROXIMATELY 08:19 PDT THE PLYMOUTH LNG FACILITY EXPERIENCED AN INTERNAL DETONATION RESULTING IN RAPID OVERPRESSURE AND SUBSEQUENT FAILURE OF PORTIONS OF THE LNG1 PURIFICATION AND REGENERATION SYSTEM, INCLUDING IN PLANT PIPING AND AN ADSORBER VESSEL,  CAUSING DAMAGE TO ADJACENT BUILDINGS AND EQUIPMENT. DEBRIS FROM THE RUPTURE PENETRATED THE OUTER WALL OF ONE OF TWO LNG STORAGE TANKS. NATURAL GAS VENTED FROM THE VAPOR SPACE BETWEEN THE INNER AND OUTER WALLS OF THE STORAGE TANK BUT DID NOT IGNITE.    STATION PERSONNEL IMMEDIATELY EXECUTED AN ESD OF THE FACILITY. OF 5 EMPLOYEES TAKEN TO THE HOSPITAL FOR EVALUATION, 4 EMPLOYEES WERE TREATED AND RELEASED AND 1 EMPLOYEE WAS ADMITTED FOR BURN INJURIES AND RELEASED SEVERAL DAYS LATER.      A THIRD PARTY INVESTIGATION FIRM WAS CONTRACTED TO DOCUMENT THE INCIDENT LOCATION AND MANAGE ALL EVIDENCE.  VARIOUS CONSULTANTS WERE ENGAGED IN THE COMPLETION OF AN INCIDENT INVESTIGATION.  THE INVESTIGATION DETERMINED THE LEADING CAUSE WAS THE PRESENCE OF A FUEL/AIR MIXTURE REMAINING IN THE SYSTEM FOLLOWING MAINTENANCE ACTIVITIES. THE FUEL/AIR MIX THEN AUTO-IGNITED WITHIN THE SYSTEM PIPING UPON STARTUP WHEN THE FLAMMABLE MIXTURE ENTERED THE INLET OF A SALT BATH HEATER.
		if (fgets (buffer, 16384, f)) {

			while (fgets (buffer, 16384, f)) {
				data = buffer;
				data.tokenize (",", &tokens, true, false);

				if (tokens.size () == 162) {
					leak = liquified_natural_gas->create_new (MAP_OBJECT_POINT);
					leak->id = atol (tokens [3].get_text_ascii ()); // REPORT_NUMBER
					leak->attributes_numeric [0]  = atol (tokens [7].get_text_ascii ()); // Operator_ID
					leak->attributes_text [0] = tokens[13]; // Local_DateTime

					if (tokens [24].get_length () > 0)
						leak->attributes_numeric [1] = atof (tokens [24].get_text_ascii ()); // UNINTENTIONAL_RELEASE
					if (tokens [51].get_length () > 0)
						leak->latitude = (long) (atof (tokens [51].get_text_ascii ()) * 1.0e6); // Location_Latitude 
					if (tokens [52].get_length () > 0)
						leak->longitude = (long) (atof (tokens [52].get_text_ascii ()) * 1.0e6); // Location_Longitude

					liquified_natural_gas->objects.push_back (leak);
				}
				else {
					log += "ERROR, unable to parse liquified natural gas data \"";
					log += buffer;
					log += "\"\n";
				}
			}
		}

		fclose (f);
		return true;
	}
	else {
		log += "ERROR, can't open Liquified Natural Gas file \"";
		log += filename;
		log += "\".\n";
		return false;
	}
}

bool PipelineAccidents::read_csv
	(const dynamic_string &path_pipelines,
	const int incident_type,
	dynamic_map *map,
	interface_window *view,
	dynamic_string &log)

{
	dynamic_string filename_gd, filename_gg, filename_hl, filename_lng;

	if ((incident_type == -1)
	|| (incident_type == 1)) {
		gas_distribution = map->create_new (MAP_OBJECT_POINT);
		gas_distribution->name = "Gas Distribution";
		gas_distribution->attribute_count_numeric = 2;
		gas_distribution->attribute_count_text = 1;
		gas_distribution->draw_as = MAP_OBJECT_DRAW_SYMBOL_LAYER_COLOR;
		gas_distribution->color = RGB (0, 255, 0);
		gas_distribution->column_names_numeric.push_back ("OPERATOR_ID");
		gas_distribution->column_names_numeric.push_back ("UNINTENTIONAL_RELEASE");
		gas_distribution->column_names_text.push_back ("LOCAL_DATETIME");
		gas_distribution->initialize_attributes = true;
		map->layers.push_back (gas_distribution);
		filename_gd = path_pipelines + "gd2010toPresent.csv";
		read_gas_distribution (filename_gd, view, log);
	}

	if ((incident_type == -1)
	|| (incident_type == 2)) {
		gas_gathering = map->create_new (MAP_OBJECT_POINT);
		gas_gathering->name = "Gas Gathering";
		gas_gathering->attribute_count_numeric = 2;
		gas_gathering->attribute_count_text = 1;
		gas_gathering->draw_as = MAP_OBJECT_DRAW_SYMBOL_LAYER_COLOR;
		gas_gathering->color = RGB (0, 255, 0);
		gas_gathering->column_names_numeric.push_back ("OPERATOR_ID");
		gas_gathering->column_names_numeric.push_back ("UNINTENTIONAL_RELEASE");
		gas_gathering->column_names_text.push_back ("LOCAL_DATETIME");
		gas_gathering->initialize_attributes = true;
		map->layers.push_back (gas_gathering);
		filename_gg = path_pipelines + "gtggungs2010toPresent.csv";
		read_gas_gathering (filename_gg, view, log);
	}

	if ((incident_type == -1)
	|| (incident_type == 3)) {
		hazardous_liquid = map->create_new (MAP_OBJECT_POINT);
		hazardous_liquid->name = "Hazardous Liquid";
		hazardous_liquid->attribute_count_numeric = 2;
		hazardous_liquid->attribute_count_text = 1;
		hazardous_liquid->draw_as = MAP_OBJECT_DRAW_SYMBOL_LAYER_COLOR;
		hazardous_liquid->color = RGB (0, 255, 0);
		hazardous_liquid->column_names_numeric.push_back ("OPERATOR_ID");
		hazardous_liquid->column_names_numeric.push_back ("UNINTENTIONAL_RELEASE");
		hazardous_liquid->column_names_text.push_back ("LOCAL_DATETIME");
		hazardous_liquid->initialize_attributes = true;
		map->layers.push_back (hazardous_liquid);
		filename_hl = path_pipelines + "hl2010toPresent.csv";
		read_hazardous_liquid (filename_hl, view, log);
	}

	if ((incident_type == -1)
	|| (incident_type == 4)) {
		liquified_natural_gas = map->create_new (MAP_OBJECT_POINT);
		liquified_natural_gas->name = "Liquid Natural Gas";
		liquified_natural_gas->attribute_count_numeric = 2;
		liquified_natural_gas->attribute_count_text = 1;
		liquified_natural_gas->draw_as = MAP_OBJECT_DRAW_SYMBOL_LAYER_COLOR;
		liquified_natural_gas->color = RGB (0, 255, 0);
		liquified_natural_gas->column_names_numeric.push_back ("OPERATOR_ID");
		liquified_natural_gas->column_names_numeric.push_back ("UNINTENTIONAL_RELEASE");
		liquified_natural_gas->column_names_text.push_back ("LOCAL_DATETIME");
		liquified_natural_gas->initialize_attributes = true;
		map->layers.push_back (liquified_natural_gas);
		filename_lng = path_pipelines + "lng2011toPresent.csv";
		read_liquified_natural_gas (filename_lng, view, log);
	}

	return true;
}

void PipelineAccidents::dump_incidents
	(dynamic_string &log)

{
	std::vector <map_object *>::iterator leak;
	dynamic_string report;

	for (leak = gas_distribution->objects.begin ();
	leak != gas_distribution->objects.end ();
	++leak) {
		report.add_formatted ("%ld", (*leak)->id); // REPORT_NUMBER

		report += "\t";
		report += (*leak)->attributes_text[0]; // Local_DateTime
		report.add_formatted ("\t%.6lf\n", (*leak)->attributes_numeric[1]); // Unintentional_Release
	}

	log += "\n";
	for (leak = gas_gathering->objects.begin ();
	leak != gas_gathering->objects.end ();
	++leak) {
		report.add_formatted ("%ld", (*leak)->id); // REPORT_NUMBER

		report += "\t";
		report += (*leak)->attributes_text[0]; // Local_DateTime
		report.add_formatted ("\t%.6lf\n", (*leak)->attributes_numeric[1]); // Unintentional_Release
	}

	log += "\n";
	for (leak = hazardous_liquid->objects.begin ();
	leak != hazardous_liquid->objects.end ();
	++leak) {
		report.add_formatted ("%ld", (*leak)->id); // REPORT_NUMBER

		report += "\t";
		report += (*leak)->attributes_text[0]; // Local_DateTime
		report.add_formatted ("\t%.6lf\n", (*leak)->attributes_numeric[1]); // Unintentional_Release
	}

	log += "\n";
	for (leak = liquified_natural_gas->objects.begin ();
	leak != liquified_natural_gas->objects.end ();
	++leak) {
		report.add_formatted ("%ld", (*leak)->id); // REPORT_NUMBER

		report += "\t";
		report += (*leak)->attributes_text[0]; // Local_DateTime
		report.add_formatted ("\t%.6lf\n", (*leak)->attributes_numeric[1]); // Unintentional_Release
	}

	log += "\n";
	log += report;
}

void PipelineAccidents::count_within_radius
	(class map_layer *zillow_sales,
	const double radius_miles,
	const int incident_type,
	const int inspect_id,
	class interface_window *view,
	dynamic_string &log)

// Count of each type of incident within 10 miles

{
	int index_gas_distribution;
	std::vector <map_object *>::iterator sale, spill;
	logical_coordinate sale_location, spill_location;
	double distance_m, ten_miles_m_plus, cutoff_radius_m, offset_10_plus;
	bounding_cube ten_mile_box;
	bool inspect;
	int attribute_offset;

	view->update_progress ("Counting Incidents <= 10 mi.", 0);

	index_gas_distribution = zillow_sales->attribute_count_numeric;
	if (incident_type == -1)
		zillow_sales->resize (index_gas_distribution + 4, zillow_sales->attribute_count_text);
	else
		if (incident_type == 1)
			// Don't increase attribute size for #2, #3, #4
			zillow_sales->resize (index_gas_distribution + 1, zillow_sales->attribute_count_text);

	ten_miles_m_plus = (radius_miles + 0.01) * METERS_PER_MILE; // a little extra so precision of distance meters is more important than offset_longitude_meters/offset_latitude_meters
	cutoff_radius_m = radius_miles * METERS_PER_MILE;

	for (sale = zillow_sales->objects.begin ();
	sale != zillow_sales->objects.end ();
	++sale) {
		view->update_progress ((*sale)->attributes_text [0], 1);

		if ((*sale)->id == inspect_id) {
			inspect = true;
			log.add_formatted ("Inspect <=10 miles\t%ld\tFirst Index\t%d\n", (*sale)->id, index_gas_distribution);
		}
		else
			inspect = false;
		
		sale_location.x = (double) (*sale)->longitude / 1.0e6;
		sale_location.y = (double) (*sale)->latitude / 1.0e6;

		// ten_mile_box needs to be 20 x 20 miles
		offset_10_plus = offset_longitude_meters (sale_location, ten_miles_m_plus);
		ten_mile_box.x [0] = (sale_location.x - offset_10_plus) * 1.0e6;
		ten_mile_box.x [1] = (sale_location.x + offset_10_plus) * 1.0e6;
		offset_10_plus = offset_latitude_meters (sale_location, ten_miles_m_plus);
		ten_mile_box.y [0] = (sale_location.y - offset_10_plus) * 1.0e6;
		ten_mile_box.y [1] = (sale_location.y + offset_10_plus) * 1.0e6;

		attribute_offset = 0;

		if ((incident_type == -1)
		|| (incident_type == 1)) {
			for (spill = gas_distribution->objects.begin ();
			spill != gas_distribution->objects.end ();
			++spill) {
				if ((*spill)->overlaps_logical (&ten_mile_box)) {
					spill_location.x = (double) (*spill)->longitude / 1.0e6;
					spill_location.y = (double) (*spill)->latitude / 1.0e6;
					if ((distance_m = distance_meters (sale_location, spill_location)) <= cutoff_radius_m) {
						(*sale)->attributes_numeric[index_gas_distribution + attribute_offset] += 1.0;
						if (inspect)
							log.add_formatted ("\t%ld\t%.2lf", (*spill)->id, distance_m);
					}
				}
			}
			if (inspect)
				log += "\n";
		}
		if (incident_type == -1)
			++attribute_offset;

		if ((incident_type == -1)
		|| (incident_type == 2)) {
			for (spill = gas_gathering->objects.begin ();
			spill != gas_gathering->objects.end ();
			++spill) {
				if ((*spill)->overlaps_logical (&ten_mile_box)) {
					spill_location.x = (double) (*spill)->longitude / 1.0e6;
					spill_location.y = (double) (*spill)->latitude / 1.0e6;
					if ((distance_m = distance_meters (sale_location, spill_location)) <= cutoff_radius_m) {
						(*sale)->attributes_numeric[index_gas_distribution + attribute_offset] += 1.0;
						if (inspect)
							log.add_formatted ("\t%ld\t%.2lf", (*spill)->id, distance_m);
					}
				}
			}
			if (inspect)
				log += "\n";
		}
		if (incident_type == -1)
			++attribute_offset;

		if ((incident_type == -1)
		|| (incident_type == 3)) {
			for (spill = hazardous_liquid->objects.begin ();
			spill != hazardous_liquid->objects.end ();
			++spill) {
				if ((*spill)->overlaps_logical (&ten_mile_box)) {
					spill_location.x = (double) (*spill)->longitude / 1.0e6;
					spill_location.y = (double) (*spill)->latitude / 1.0e6;
					if ((distance_m = distance_meters (sale_location, spill_location)) <= cutoff_radius_m) {
						(*sale)->attributes_numeric[index_gas_distribution + attribute_offset] += 1.0;
						if (inspect)
							log.add_formatted ("\t%ld\t%.2lf", (*spill)->id, distance_m);
					}
				}
			}
			if (inspect)
				log += "\n";
		}
		if (incident_type == -1)
			++attribute_offset;

		if ((incident_type == -1)
		|| (incident_type == 4)) {
			for (spill = liquified_natural_gas->objects.begin ();
			spill != liquified_natural_gas->objects.end ();
			++spill) {
				if ((*spill)->overlaps_logical (&ten_mile_box)) {
					spill_location.x = (double) (*spill)->longitude / 1.0e6;
					spill_location.y = (double) (*spill)->latitude / 1.0e6;
					if ((distance_m = distance_meters (sale_location, spill_location)) <= cutoff_radius_m) {
						(*sale)->attributes_numeric[index_gas_distribution + attribute_offset] += 1.0;
						if (inspect)
							log.add_formatted ("\t%ld\t%.2lf", (*spill)->id, distance_m);
					}
				}
			}
			if (inspect)
				log += "\n\n";
		}
	}
}
